### ISSUE TITLE
Typo / Disambiguation

### ISSUE THREAD

**Issue by smalich** [w3c/wot-architecture#1]
5.4.2 Smart home: Legacy device
Fig.6 shows an example of WoT servient on cloud server that controls a legacy electronic appliance through a home hub.
In this case, WoT servient on cloud **_cashes_** properties of electric appliances that a home hub manages and acts as an agent that manages them in the cloud in conjunction with the home hub

'cashes' should be 'caches', right? ;-)

**Comment by knimura** [comment]
My mistake. Thank you for pointing it out.

**Comment by mkovatsc** [comment]
Fixed -> closing
