### ISSUE TITLE
Fig.2 Protocol Binding Structure

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#10]
With some distance after the F2F, [Fig.2](https://w3c.github.io/wot-architecture/images/protocol-binding-concept.png) does not really fit what we discussed (according to my memory). I saw an important step forward in the insight that there is no differentiation between "WoT protocols" and "non-WoT protocols". We have to describe in any case, in some cases it is just easier (when people use Internet+Web standards without custom edits).

Fig.2, however, shows oneM2M vs OCF vs WoT Device.

Kaz's handdrawn picture was better in the sense, as it reflected that there is no "standard WoT binding" that we have to translate to.

**Comment by draggett** [comment]
+1 to avoiding such differentiation

**Comment by knimura** [comment]
Fig.2 shows the arrows pointing from “Other device’s TD” to both App Logic and Protocol Binding (Common). As specified in Scripting API document, it has API for handling a TD; “By consuming a TD, a Thing creates a runtime resource model…” So an arrow would point from “Other device’s TD” to “Runtime” to keep the consistency.

**Comment by mkovatsc** [comment]
I have redrawn the figures in a common style (taken from presentations and white paper) and stumbled upon this problem: we have different views and it is virtually impossible to cover this in a single figure (e.g., a "Scripting API" block explains what the deliverable is about, but technically it is a "Runtime System" block). I will try to show these figures in today's Editors call, and tweak them to address @knimura 's input.

**Comment by mkovatsc** [comment]
See #23 for fix.
