### ISSUE TITLE
Industrial Section: Image sources needed

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-architecture#100]
I promised to update the introductory text and the image of the section  https://w3c.github.io/wot-architecture/#industrialiotusecases

Where can I find the sources of the Figure 1 Smart Factory? I just find the png file.

**Comment by k-toumura** [comment]
> Where can I find the sources of the Figure 1 Smart Factory? I just find the png file.

[Here](https://github.com/w3c/wot-architecture/raw/master/images/wot-use-cases/wot-use-cases.pptx) is source of the Figure 1 (and others).

**Comment by sebastiankb** [comment]
@k-toumura thanks
