### ISSUE TITLE
Rewrite section "4.2.3 Remote Access"

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#106]
Must rewrite for remote access/control use case. Include changing uplink connectivity.

**Comment by mkovatsc** [comment]
See Princeton F2F minutes (ed note is ad hoc summary).

The main point of the use case is that clients need to remote control devices in a local network. The uplink of those device might change or they might be behind a NAT.

A gateway that registers with a cloud service is one solution to this requirement. Thus, 4.2.4 has to focus more on the fact that there might be need for a local box for any kind of purpose, not only solving remote access (see https://github.com/w3c/wot-architecture/issues/107).
