### ISSUE TITLE
Rewrite Section 4.2.4 Gateways

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#107]
The editor's note reads: Must rewrite for local box/compute node use case.

Suggest to create a new section "edge device"

**Comment by mkovatsc** [comment]
Find details in the Princeton F2F minutes. The problem was the overloaded meaning of gateway. Others such as Mozilla use this term for the "local box", but they also heavily rely on individual protocol translation by this box, i.e., a gateway in the classic sense.

**Comment by mkovatsc** [comment]
Note that the "local box" is neither solely for solving remote access (see https://github.com/w3c/wot-architecture/issues/106). Another point was that there are many reasons to have it, which need to be mentioned in the text. Hence, "edge device" might be a good choice.

**Comment by mlagally** [comment]
@mkovatsc I added a new section on edge devices and cleaned up the gateway section:
See:
https://github.com/w3c/wot-architecture/pull/126
