### ISSUE TITLE
Create Architecture explanation document

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#117]
Please add text to the appropriate section of the Explanation document:
"WoT Architecture - Explanation for TAG review.md"

https://github.com/w3c/wot-architecture/blob/master/proposals/WoT%20Architecture%20-%20Explanation%20for%20TAG%20review.md

**Comment by mkovatsc** [comment]
I am sorry that I missed the corresponding call, but I really cannot see what needs to be done, who is responsible for which section, or even how the linked .md should correspond to the required explanation document (abstract+intro from original document, huge use case section, completely different building block illustration, explainers for the other WoT documents).

@ashimura Via the agenda in the wiki, I found this document:
https://github.com/w3c/vc-data-model/blob/gh-pages/VCDMExplainer.md

From that I take the following structure we would need:

* Short introduction
* Goals / non-goals
* Most important terms/concepts ("getting started")
* Short list of illustrating use cases with examples (they have a Code Samples section, but does not apply to our arch doc; we should maybe use the stuff from our Annex B)
* Important Design Choices
* Features at Risk
* Implementations and Reviews
* References and Acknowledgements

@mlagally mentioned something about a simplified structure, but the linked .md above rather looks like a copy of our original document.

Can someone explain what was planned?

**Comment by mlagally** [comment]
@mkovatsc Here's a guideline on what should be in an explainer document:
https://w3ctag.github.io/explainers

It contains links to various examples where each group has picked the appropriate sections, 
i.e. there is no common structure across these documents.
Look for example at:
https://github.com/WICG/web-share/blob/master/docs/explainer.md
https://github.com/WICG/visual-viewport/blob/gh-pages/README.md

We started with a simple structure, i.e. consisting of:

- Introduction
- Use cases
- What is being standardised

I added an introduction section, which we initially assigned to you,  
yesterday evening as a placeholder, since I was not sure whether you find time for the writeup. 
I agree with your that we should be more in-line with the suggested form from the document above.
However since we will have two WoT documents with corresponding explainers, 
there will be some overlap, e.g. features at risk I would clearly see in the explainer 
for the *TD document* and not in the architecture explainer.

I'll take another iteration at the document structure today and hope we will end up 
with a document that serves the purpose of the TAG review.

**Comment by mlagally** [comment]
@mkovatsc @mmccool 
Please review https://github.com/w3c/wot-architecture/pull/122
This is more aligned with the proposed structure.
There are some section that need to be written/additional input , i.e.:

- Goals
- Non-goals
- Getting started / example code
- Key scenarios

@mkovatsc Can you please take a stab at them?

**Comment by mkovatsc** [comment]
> 1. By enabling and enhancing machine-to-machine communication, as devices can
   read WoT Thing Descriptions and use the information contained in them
   to automatically adapt to details of a particular protocol, using
   the interaction/protocol binding abstraction.
> 2. By serving as a common, uniform format for developers to document and
   retrieve all details necessary to access an IoT service and make use of that service's data.

These seem to be the main goals of the WoT Thing Description. @sebastiankb , can you use this?
