### ISSUE TITLE
6. Mapping variations: Web browser

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#12]
While an example involving the Web browser is probably quite catchy, the technical details are a bit confusing: for now, there is no WoT support out-of-the-box in Web browsers and they cannot speak the given examples, but "only" HTTP(S), FILE, FTP, and RTP(S).

I see two possible remedies for now:
1) Explain how this would work using a JS library (for parsing the TD and providing the Scripting API) and AJAX/XMLHttpRequestObject (as Protocol Binding).
2) Use a different WoT client.

**Comment by draggett** [comment]
Including an example with a Web browser is valuable as it shows how browsers can be used to provide the user interface for a web of things service. Yes, we can note that it requires a library, and  is restricted to browser supported protocols, e.g. HTTP, Server-sent events, WebSockets and WebRTC. This would be particularly interesting to Web developers.

**Comment by mmccool** [comment]
The definitions section explictly refers to "web servers".   There is also confusion between "Thing" and "Servient".   The architecture document seems to use Thing to refer to physical hardware (eg Local Hardware), whereas my understanding was that a "WoT Servient" was just a particular implementation of a Thing.  In my view a Thing should be anything that can be given a Thing Description.  It's clear that WoT Servients are therefore Things with that definition.   But can there be Things that are not WoT Servients, eg. Local Hardware or Legacy Devices?   They can still be given partial Thing Descriptions (eg for access via the Scripting API) but it may not be possible to give them Protocol Bindings, etc.

**Comment by mkovatsc** [comment]
A Servient is an implementation from scratch that follows the WoT architecture. It can expose multiple Things and can provide local hardware as Things to be consumed locally.
A Thing is anything that can be described with a Thing Description (e.g., also existing devices that do not take the WoT architecture into account).

**Comment by draggett** [comment]
> But can there be Things that are not WoT Servients, eg. Local Hardware or Legacy Devices? They can still be given partial Thing Descriptions (eg for access via the Scripting API) but it may not be possible to give them Protocol Bindings, etc.

Hmm, that presumes a particular mindset for protocol bindings.  I think it is more helpful to talk about the metadata needed for accessing a thing. Some examples will make this clearer.

Consider a gateway/hub implemented in NodeJS and running on the local area network. You can install apps on this hub from the cloud.  One class of such apps exposes sensors on the hub's local hardware as things for other apps installed on the hub, or for web pages running on browsers e.g. smart phones that are connected to the local area network.

If another app on the hub wants to access the thing, it asks the hub to provide the corresponding object given the thing's URI.  For this no communications metadata is needed.  Now consider a web application running on the smart phone. It loads the application from the web server on the hub, and the web page script asks a web page library to provide an object for the thing given its URI. The library retrieves the thing description from the hub over HTTP, and learns that it should be accessed over WebSockets (or perhaps via HTTP + Server-Sent Events). The web page script never needs to see details of the protocol binding.

Now let's consider an application that wants to interact with a home appliance like a washing machine. The washing machine has an embedded CoAP server. This is accessed by the gateway / hub which exposes the washing machine as a thing for local apps on the hub, or for apps running as web pages on smart phones.  The washing machine manufacturer or a third party acting on their behalf provides an app that people can install on their hubs. This app comprises the code that talks to the washing machine over CoAP and exposes it as a software object to other apps on the hub, and to web pages over web browser protocols.

The washing machine manufacturer may also want to expose the device via the cloud. Doing so directly runs into security challenges, so it may be preferable to use a gateway in the home. This can be achieved in a very similar way to the approach described in the previous paragraph. The manufacturer provides an app that is installed on the gateway. It uses CoAP to talk to the washing machine, and web protocols to talk to the cloud server which in turn hosts apps for access by other apps and web pages etc.

This raises the idea of declarative bindings for bridging protocols at least for standard protocols. The washing machine manufacture provides a thing description with the interaction model, and several sets of communication patterns: one for using CoAP to talk to the washing machine, another for access via web protocols from browsers on the local area network, and yet another for re-publishing the thing on a cloud server.

By declarative bindings, I just mean metadata that the host platform can use to identify a driver and provide to that driver. This includes metadata for dealing with devices that sleep a lot, and which buffer up sensor readings and so forth.

**Comment by mkovatsc** [comment]
Original purpose was killed, closing my issue.
