### ISSUE TITLE
6. Mapping variations: Security and Privacy boxes in figures

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#13]
The "Security and Privacy" box around the Servient figure was meant to indicate that we also look into the security considerations. In Section 6, this box looks like we, that is WoT technology, takes care of the secure channel between two Servients. However, that must come from the binding, as we only describe how to use the already provided security (except for TD securing and internal issues for the runtime). Furthermore, the box is quite confusing, when the black dashed box is used in addition to indicate device boundaries...

I would remove the "Security and Privacy" box and rather have good security considerations in the text -- and use details such as "HTTPS" instead of "HTTP"...

**Comment by mmccool** [comment]
Yeah, putting a dotted line in the diagram is not actually how you implement security ;).

I propose we just take out all the security items from the diagram and deal with it in the text.   We can discuss how to deal with this in the next Security TF call, too.

**Comment by mkovatsc** [comment]
See #23 for fix.
