### ISSUE TITLE
Clarify WoT Runtime vs other known runtimes

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-architecture#130]
WoT uses the word "Runtime" in a less than well defined manner.
We should explore and use terminology from other runtime environments.
Since the current reference implementation is TypeScript, the first runtime environment to check is ECMAScript. In particular, the following notions should be mapped/discussed:
- [execution context](https://tc39.github.io/ecma262/#sec-executable-code-and-execution-contexts)
- [agent](https://tc39.github.io/ecma262/#sec-agents)
- [built-in objects](https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects), e.g. the [global object](https://tc39.github.io/ecma262/#sec-global-object)
- [data types/structured data](https://tc39.github.io/ecma262/#sec-global-object) in conformance with TD definitions
- [control abstractions](https://tc39.github.io/ecma262/#sec-control-abstraction-objects), e.g. Promise
- the HTTP operations/client library used (e.g. fetch())
- and possibly other things.

I also propose merging Section 8 (some Servient implementation details, not much text, repeated sentences) into Section 7 (Building Blocks), split where it applies. IMHO in general the Architecture doc should be more about the building blocks rather than specific implementation issues, but when the latter arise, could be encapsulated in the building blocks text. Maybe Implementation Guidelines are also needed, but then the current Section 8 is not exactly that.
(this might be split in another issue).

**Comment by zolkis** [comment]
Related to #83

**Comment by mlagally** [comment]
As discussed in arch call on 14.3.:

The current WoT runtime definition is language independent by intention:
A runtime system for application scripts with the WoT Scripting API. Implementing a WoT Runtime is optional for Servients. The WoT Runtime should be the component that instantiates Consumed Things and Exposed Things as software objects, manages their state, and generates the TDs. It communicates with other components such as the Binding implementations and application scripts (the WoT Scripting API being one way).

We should not limit it to a specific language / execution environment.
Would a different term help to resolve your concerns (e.g. WoT Runtime Context)?

The split between chapter 7 and chapter 8 is intentional to separate Servient implementation from building blocks.

**Comment by zolkis** [comment]
Right, the WoT Runtime is language independent, but we need to operate with generic runtime concepts, such as the ones enumerated above. This is important e.g. for security considerations. The WoT Runtime imposes a set of constraints on top of generic runtimes. It is important to specify what are those.

The reference WoT scripting implementation is TypeScript, meaning one agent, sequential execution of scripts, but with extra constraints: the ECMAScript runtime would be able to handle scripts included in a TD, but the WoT runtime does constrain that.

Apart from that, there are other things to clarify. Currently we say the servient implements the WoT network interface. That means it can consume and expose Things. It can fetch, validate, it will de-facto create internal objects - everything we say a scripting runtime (also) does. The options on how those objects are managed should be clarified: whether privately (i.e. no Scripting Runtime) or using a scrpting runtime, and which one. Since what runtimes do is manage these operations, it would make sense to call the generic entity a WoT Runtime and not just servient implementation.

That is why in my original proposal I called the WoT Runtime the entity that implements the WoT interactions (on network level). How is it implemented it's up to the manufacturers, its internal objects are encapsulated. But a part of the WoT runtime may be standarized to use standardized internal objects, such as Scripting Runtime objects (in general). Furthermore, in particular a WoT Runtime may use ECMAScript, Lua, Python etc runtimes, while still having to implement isomorphic objects (ConsumedThing, ExposedThing) in them. It's a layered model with all layers using the same terms and implementing the same functionality at different standardization level.

**Comment by zolkis** [comment]
Right now we are standardizing on the Web Platform, which means a very specific and well defined runtime. However, we want to fit a much more general concept on top of it, which won't work.

On the other hand, there is not much interest in scripting per se. Even on last Scripting call there were questions what is the actual use case for scripts. My answer was the current Scripting API is a specification on how to make a specific implementation (on the Web Platform) of the generic WoT Runtime. However, we don't have the concepts and vocabulary laid down for this sentence, because the concepts we have are Servient (meaning all software stack) and optional Scripting Runtime (which is a not well defined sub-class of an undefined generic class).

**Comment by mmccool** [comment]
So, I tried to come up with a PR to sort this out but everything I tried to reorganize the document painted me into one corner or another and I had to abandon it.   I went off and thought about it and here is what I think we should do:
1. The current definition of "WoT Runtime" *requires* use of the WoT Scripting API and is an "internal view".   I tried to redefine it to be more abstract but that runs into a whole raft of complications throughout the document.   For example, if you want to talk about something implementing the behavior of a Thing but not specify how, use of "WoT Runtime" runs into all kinds of contradictions.  Since we don't have a whole lot of time to clean up this document I propose we KEEP the current definition: the WoT Runtime uses and supports the WoT Scripting API.
2. The current definition of WoT Runtime however also includes some other functionality unrelated to the WoT Scripting API, such as maintenance of secrets like provisioned security keys.   It MAY also support other functionality like generating and consuming TDs (saying it may not, but that TDs may be generated elsewhere and associated with the Thing, gets tricky due to certain RFC2119 asssertions in the spec saying that TDs must "originate" with the Thing... I'll return to that).   To resolve this, and support "native" implementations of Thing behavior that are NOT implemented using the Scripting API, I propose a new term: Behavioral Agent.   (I went around and around thinking of a name for this; Application Context, Application, Behavioral Context, etc.   Let's just go with this for now and fight about it later).   I will draw a picture and link it here to explain, but basically a Behavioral Context manages private security information and hosts one or more Execution Environments, each of which are protected from each other (if there are more than one) and (ideally...) cannot access the security keying information directly; an Execution Context can *optionally* host a WoT Runtime.   A *native* implementation provides some other implementation that performs the same functions as a WoT Runtime externally but the spec does not otherwise constrain its internal implementation.

Part of the challenge I am having here is that part of the current document reads like it is very prescriptive and talks about specific implementation requirements for a WoT Thing, and other parts are (IMO, properly) descriptive and just state *external* requirements for a WoT Thing (it must have a Thing Description that describes its affordances, etc).   I think both are reasonable points of view...  I think we have waffled a lot on this and we may want to go back to talk about WoT Servients as being a specific kind of implementation that is more prescriptive in nature (and can do things like have a full WoT Runtime, be able to consume TDs, etc. etc).   But I would prefer it if the core specification supports first-class status for "WoT Things" that may in fact be devices from another ecosystem that are just described with TDs.

**Comment by mmccool** [comment]
Regarding the RFC2119 assertion saying that "TDs must originate with the Thing" I want to broaden that a bit to say "TDs must originate with a Thing or be uniquely associated with a particular instance of a Thing".   This should also be associated with some explanation that if a Thing itself cannot provide a TD, then there needs to be some other service associated with it that can.   I'll post this under a separate issue; it's related to this insofar as we need to define what functionality a "Thing" MUST provide, and what the responsibilities of the "Behavioral Agent" are.

**Comment by mmccool** [comment]
Please see slides 3 and 4 of https://github.com/w3c/wot-architecture/blob/master/images/wot-architecture-figures-new.pptx.   I've also broken these out as separate figures in https://github.com/w3c/wot-architecture/blob/master/images/wot-thing-runtime-scripting.png and https://github.com/w3c/wot-architecture/blob/master/images/wot-thing-agent-native.png

**Comment by mmccool** [comment]
I'll create a PR soon that incorporates these, updating the current "building blocks" sections.

**Comment by mmccool** [comment]
Images updated to include ExposedThing and ConsumedThing objects as in Matsukura-san's figures.   Also added two versions of "native" implementations: one that uses these abstractions internally, and one that does not (i.e. a brownfield device) but that can still be described "externally" with a TD.

**Comment by zolkis** [comment]
I propose the approach of making WoT architecture pictures without the Scripting API, making clear what is the expected servient functionality in implementations.

When this is clear, we can add the Scripting API as a convenience block. This will separate the concerns.

About naming and concepts (about execution contexts, secrets etc), there are already concepts defined and used in browsers/ECMAScript and it would be understandable to operate with these in a W3C WG, if possible.

The scripting requirements from the Security document IMHO match quite well with the ECMAScript runtime concepts and model, which is mappable to other runtimes as well. 

My problem with the current formulations were that a Servient seems to do the same things as a runtimes does, so we should clarify the overlaps and differences and separate the concerns.

I will think/review the linked material and compare with the browser model so that if possible, we reuse existing concepts and terms.

**Comment by mkovatsc** [comment]
> I propose the approach of making WoT architecture pictures without the Scripting API, making clear what is the expected servient functionality in implementations.

I support any simplification we can make. In my personal opinion, the proposed figures by @mmccool in https://github.com/w3c/wot-architecture/issues/130#issuecomment-474707178 are way too complex and rather raise new questions (What is an agent? What is the difference between execution environment and runtime? Why is there a Scripting API inside the runtime?).

One of the original ideas in WoT was that there can be software objects representing Things, which simplifies IoT application development. Such software objects live in a runtime environment. Hence, the WoT Runtime for me is the container for Exposed Thing and Consumed Thing object instances. The WoT Runtime system provides an API to application, which can be native or the optional Scripting API. It also takes care of serializing Exposed Things into a TD and parsing TDs to create Consumed Thing instances.

I agree with @mmccool that the implementation section should also highlight that WoT can be applied to existing devices or platforms. They basically use a native, "black box" implementation, but their network-facing interface is described by one or more TDs.

**Comment by mmccool** [comment]
See also https://github.com/w3c/wot-architecture/pull/143

**Comment by mmccool** [comment]
Matthias, I tried already to revise the document to say that the WoT Runtime may or may not use the WoT Scripting API.   There were surprisingly many places however that assumed the Runtime required the Scripting API, and there were also some things the Runtime does (like maintain private security state) that have nothing to do with scripting.   There is also a need to make the private security data inaccessible from the scripts.   However, yes, I agree that adding both an "agent" and an "execution context" adds a lot of "stuff" to the figures.   I could take another stab at the other solution to this though, which like you suggest would require redefining the WoT Runtime to fully decouple it from the Scripting API.

Anyhow, I did a PR for the option I suggested above, but if people think the other approach makes sense (decoupling the WoT Runtime and the Scripting API) I can try that instead.

**Comment by mmccool** [comment]
PS "Execution Context" is also defined in terminology.   It's not really used anywhere though and I would just suggest removing it.   I think we originally introduced it as a security boundary for multitenant things but I think this is overly complicated.   We can talk instead about instantiating more than one Thing on a physical device rather than trying to make Things themselves host multiple tenants.

**Comment by mmccool** [comment]
Anyhow, I also have "software objects" representing exposed and consumed Things inside the runtime.  However, this is an "inside the runtime" view.   They don't necessarily show up in the "native" implementations.

**Comment by mmccool** [comment]
For use in the discussion in the main call I added a couple of figures representing the option Matthias brings up: let's just say a WoT Runtime may or may not use the WoT Scripting API.   I also got rid of the Execution Context.  The old figures are still in there... I will extract the figures as PNGs if we decide to use them after the call.

https://github.com/w3c/wot-architecture/blob/master/images/wot-architecture-figures-new.pptx

**Comment by mmccool** [comment]
New images broken out:
https://github.com/w3c/wot-architecture/blob/master/images/wot-thing-scripting.png
https://github.com/w3c/wot-architecture/blob/master/images/wot-thing-native.png
https://github.com/w3c/wot-architecture/blob/master/images/wot-thing-foreign-2.png

**Comment by zolkis** [comment]
I like the new pictures. On the slide that includes scripting, we could expand a bit to make it clear that
- the "Scripting API implementation" (which may use a scripting runtime on its own, like ECMAScript or Python or Lua), represented as a bigger (sand)box that uses the Native API (and may expose some of it to scripts)
- inside the "Scripting API implementation" box there is the Scripting API box that enables scripts to use and extend the WoT Runtime functionality, so
- there could be boxes labeled "script" inside the Scripting API box.

**Comment by zolkis** [comment]
However, when introducing terms for the WoT Runtime, I would still strive to stick with established and known terms in W3C, which leads us to use ECMAScript terms when possible (some links collected in the first post [here](https://github.com/w3c/wot-architecture/issues/130#issue-420474699)). These terms are not far from other runtimes terminology (which is not well defined anyway). Also note that many IoT systems use some [implementation](https://en.wikipedia.org/wiki/List_of_ECMAScript_engines) of ECMAScript.
Generic:
https://en.wikipedia.org/wiki/Runtime_system 
https://en.wikipedia.org/wiki/Execution_model
Although there is some controversy:
https://stackoverflow.com/questions/5372852/meaning-of-runtime-environment-and-of-software-framework 
An example on what needs to be done to run [Python](https://cloud.google.com/appengine/docs/standard/python/runtime ) and [Lua](https://ieeexplore.ieee.org/document/7391213) scripts.
Quoting from the last one,

> Run-Time Environment combines Rendering, Event mechanism, Memory management, System management (OS specific), Application manager and Execution manager. ScriptModule is just a part of Execution manager which takes care of communication between Runtime Environment and Lua interpreter in order to provide custom system functionalities for Lua developers.

In the WoT Runtime IMHO we need to define a minimum set of
- runtime environment (global objects, security settings, etc)
- execution context
- software objects, which can reside in a Scripting runtime, instantiated by scrips, or could be private to and managed by the WoT Runtime.

It should be clear that the WoT Runtime implements the WoT interactions and internal SW objects, TD parsing and validation, abstracts networking (optionally via the Protocol Bindings).

The Scripting API implementation, when present, instantiates in the Scripting runtime the WoT SW objects and uses the WoT Runtime services.

Of course, the WoT Runtime and Scripting API implementation could be the very same thing, but that is an implementation detail. It might well be that we'd be required to define algorithms of the WoT Runtime in the Scripting API specification, but it should be clear where this belongs in architectural terms.

**Comment by mkovatsc** [comment]
To clarify the goal of my previous statements:
* I tried to explain my understanding of the term "WoT Runtime" to help forming a common understanding.
* A "WoT Runtime" only becomes a concern when looking at the implementation, which is only the case when our optional WoT Scripting API is considered. From the architecture view, we could even just ignore it.
* It seems, however, there should be a central definition of "WoT Runtime" to be used by the Scripting API and Security building blocks, and possible future building blocks.
* When we show *possible* implementations for adopting and combining the WoT building blocks, we should show both, a native implementation possibility and a Scripting API based implementation possibility.

**Comment by zolkis** [comment]
Also, it would be important to clarify the use cases.

In the native scenario, the WoT Runtime is fully implemented by the developer/manufacturer/solution maker.

With Scripting, the developer/manufacturer/solution maker implements the WoT Runtime in a special way, by using an adapted Scripting runtime (e.g. JerryScript, Ducktape etc) and a native framework/OS. The benefit of using Scripting API is to ease WoT Runtime implementation and deployment across a given solution or across many solutions. The purpose of standardizing the Scripting API is to maximize the number of solutions that could benefit from scripting.

**Comment by mkovatsc** [comment]
Issues I see with the figures:
* APIs are drawn inside the runtime, but APIs are the interface between application code and the runtime system
* A script is depicted inside the runtime, but scripts are application code that would use an API to interface with the runtime system
* There is an "Interaction Implementation" shown inside the runtime, but interactions within the Web of Things usually involve Protocol Bindings and messages exchanged among networked systems (consuming an ExposedThing within the same runtime directly is a special case that should not be shown).
* The "ExposedThing" and "ConsumendThing" boxes are a bit to prominent. For the Scripting API case, they can be used to depict the idea of the software objects; for the native case, there can only be virtual/imaginary ExposedThings that result from providing a TD for the de facto network-facing interface.

**Comment by zolkis** [comment]
Ideally we'd need 3 dimensional pictures. The view in Michael's slides are top view. From side view, the scripts would be above the API, which would be above the Scripting implementation, which is part of the Runtime. The Scripting Runtime is one part of the Scripting implementation.

The ExposedThing and ConsumedThing entities in the slide might correspond to SW objects, or shared libraries or any entity the Runtime operates with (loads, executes etc). IMHO it's a bit unfortunate to have the same name for these as for the SW objects owned by the Scripting Runtime. But it's also true the Runtime and Scripting implementation might be the same thing, in that case it's correct.

Perhaps we can leave out the ExposedThing and ConsumedThing entities from the Runtime, but on the other hand we need to express that we do implement those concepts and their interactions in a Runtime, together with parsing/validating a TD and instantiating these entities from TD.

**Comment by mmccool** [comment]
I took another stab at the pictures.  See my recent uploads to the images subdirectory.   First, to address the issue that my figures were too detailed and implementation specific, I created a new, more abstract picture for the building block section that leaves out things like the WoT Runtime, APIs, etc.   But it does show how certain architectural aspects (eg scripting, protocol bindings) get split up in various ways among the building blocks (for instance, public security data goes into the Thing Description, private security data needs to be inside the thing; likewise "interactions" get split up into "interaction affordances" (which are the metadata on what interactions are available and how to use them) and the actual implementations of the interactions (how the device responds, how the state is stored, etc).

I took my older pictures and modified them a bit to make them clear that they are particular *implementations* of Things and will move them to the "Implementation" section immediately following the building blocks section.  Then there will be a clear progression in the document from abstract to concrete, and it should be clear that multiple implementations are possible.

I don't think this will address *all* the concerns noted above but it should be a step forward and maybe lead to a compromise we can also agree to.

Anyhow, updating my PR right now so there is text to go along with the figures... should be ready in an hour or so.

**Comment by mlagally** [comment]
I think we should not put any constraints on the runtime that is deployed on devices/things.
We are not in a green-field environment where we can prescribe device manufacturers to adopt any specific architecture. 
There are many cases of devices in the market that are implemented in C, C++, Java and other languages.
The scripting API is useful if someone implements a new device using ECMA script.  
However we should not assume a specific implementation methodology or language, and should not be prescriptive wrt. the software design of a device.
This will limit the usability of WoT and endangers adoption.
As long as an implementation of a WoT compliant device provides a TD, it satisfies the normative requirements of WoT, i.e. the TD spec.

**Comment by zolkis** [comment]
Architecture is not normative, so we cannot prescribe anything to device manufacturers.

IMHO the point in the architecture document is to explain how WoT is meant to be used. No how it should be implemented. The architecture leaves a lot of implementation options possible, but there are some things a manufacturer should do before it can work with WoT devices. That does not mean the Arch spec prescribes anything.

What I requested was _clarification_ of terminology and functionality, given a lot of semantic overlap in the way the term _runtime_ was used.

A C implementation will have to have what we call a WoT Runtime, since it has to implement WoT functionality. So it should be fine to speak with runtime terminology.

When it comes to that, there is a multitude of runtimes out there and they are not well defined universal terminology, so we do need to be specific. I think Michael got quite a good approach on it.

There is also a point that this WG is in W3C, not in IEEE (although I have the impression sometimes that people confuse the two), so it should be fine that a first implementation is ECMAScript based and the runtime terminology follows that (given that there is no concise universal runtime terminology yet, and the ECMAScript runtime terms are quite generic to start with).

**Comment by mlagally** [comment]
PR: https://github.com/w3c/wot-architecture/pull/143#discussion_r267644697

**Comment by mlagally** [comment]
discussion was closed in call on 21.3.
