### ISSUE TITLE
Define "Web Technology" and target protocols

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#133]
We need to define what we mean by "using web technology" to make clear, as early in the document as possible, that don't mean just REST/HTTP.  In particular, we should state the requirements that we limit ourselves to protocols with resources/access points defined by URLs and with payloads that can be identified with IANA types, and then we need to "survey" a set of target standards (OPC-UA, OCF, etc) and point out that these constraints still allow us to address the majority of IoT standards (eg rather than starting from use cases, which is good for built-from-scratch WoT things, we need to support the requirements for "supporting existing devices and devices from other standards").

**Comment by mmccool** [comment]
Actually, the requirements for "web technology" are covered later in the document (with some specific RFC2119 assertions) but there is some ambiguity here and there in the document.    Forward references and/or an explict definition under "terminology" might help.   The danger is readers may equate "web" and "HTTP" which is not USUALLY the intent in *this* document.

**Comment by mlagally** [comment]
Call on 21.3.
This should be part of editorial update:
Clean up to make sure that web technology is not limited to REST/HTTP.
