### ISSUE TITLE
Support Patterns without Local Proxies

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#134]
All the "common patterns" assume a local proxy, i.e. they require a service running on a gateway.   At least it looks that way... unless the local proxy is actually combined with the device.

Can there be a pattern where the device "registers" itself directly with a cloud service/remote proxy?  In practice I think this pattern is quite common.

**Comment by mmccool** [comment]
To clarify, when I did the "register with a remote proxy" implementation, I actually set up a reverse tunnel to access the remote proxy; which in fact is a kind of local proxy.   So maybe we just need to explain different ways to implement "local proxies".

**Comment by mmccool** [comment]
Part of what I added to PR https://github.com/w3c/wot-architecture/pull/176 addresses most of this, eg. when a local Servient acts as a client and connects to an external remote Servient to set up a tunnel.
Doing without a local proxy at all would require every device to support a tunneling protocol which is maybe NOT a good thing... more of an anti-pattern, really.

**Comment by mlagally** [comment]
See https://github.com/w3c/wot-architecture/pull/319
