### ISSUE TITLE
Don't enforce server paradigm on devices

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#146]
Use-cases which involve multiple devices, e.g. multiple servers don't require adopting a server model in the thing. Instead they take the active, i.e. client role and initiate the connection with the cloud. This improves the scalability and is a requirement for several deployments.

**Comment by mlagally** [comment]
Todo:
* need to add a requirement: endpoint devices can be clients or servers
* add language to servients chapter 8

**Comment by mlagally** [comment]
PR: https://github.com/w3c/wot-architecture/pull/173

**Comment by mmccool** [comment]
PR https://github.com/w3c/wot-architecture/pull/176 also addresses this (partly) in section 9.   Some more figures would help in the final version; there are some scenarios I added (eg non-editorial context...) as "in more complex cases" paragraphs.
