### ISSUE TITLE
Editorial work

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#153]
Tasks:
* Align annex A and B with the terminology in the previous chapters
* review and resolve all open editors notes
* ~~Tabs are messed up in many places. Editors should be set to convert tabs to spaces.~~
* ~~Fix terminology~~
* ~~Add forward references to chapters in the introductory section~~
* Add links to terminology terms throughout the document
* ~~Delete all snippets~~
* Use UK or US english consistently

**Comment by mlagally** [comment]
PR that addresses the strike out tasks: https://github.com/w3c/wot-architecture/pull/169

**Comment by mmccool** [comment]
I did a spell check in PR https://github.com/w3c/wot-architecture/pull/176 and removed all the British/Canadian spellings, although it pains me.  Going the other way is more work (the figures use American spelling, eg Behavior vs Behaviour) so I hope American spelling is the correct choice.
