### ISSUE TITLE
Terminology missing/inconsistent

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#17]
The terminology used in this document is somewhat inconsistent with what I understood to be our consensus.  For instance, does a Thing Description describe a Thing?   Is a WoT Servient a kind of WoT Thing?   Are there Things that are not WoT Servients (or WoT Servers)?   Etc.

Also there are some terms that are used (like Thing) but not included in the list of definitions.

Finally the original definition of "WoT Server" was defined in terms of "web server" which is just wrong (it could, for instance, be a CoAP server).

I added some definitions in my last pull request but it needs a going-over.

Also, there is the question of whether we should be defining such WoT terms here or elsewhere in a document we can all refer to.

**Comment by mmccool** [comment]
I assume we want to move further discussion here: https://github.com/w3c/wot-architecture/blob/master/terminology.md
I'm happy with the current definition of Thing, mostly (see my comments)

**Comment by mkovatsc** [comment]
In the editors call on 30 Aug 2017 we concluded to keep the Markdown while we still work on the definitions.
The Architecture FPWD will link to the Markdown.
The other FPWDs will link to the Architecture document (where the content from the Markdown will ultimately be merged).
