### ISSUE TITLE
Use "Exposed Thing" and "Consumed Thing" consistently

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#171]
When working on PR https://github.com/w3c/wot-architecture/pull/170 I updated the definition of Consumed Thing and Exposed Thing to refer to *either* abstraction in the WoT Runtime *or* actual software objects created and managed by the Scripting API.   This is because these terms are used in both these senses in the text.

However, there are many cases where "ExposedThing" and "ConsumedThing" are used without spaces to also refer to these abstractions/objects.  These do not show up as errors since these instances do not have "a" anchor tags around them.  However, for consistency they should be revised to (a) include the space and be written as "Exposed Thing" and "Consumed Thing" respectively (b) by surrounded by "a" anchor tags.

Our other option would be to use one version for the abstraction and one for the actual objects but that will be pretty hard to do right in the time we have left.

**Comment by mmccool** [comment]
We could also go the other way and use "ExposedThing" and "ConsumedThing" consistently.  This would be less consistent with other terms like "Protocol Binding" but is probably more consistent with the use of these terms as the names of objects, eg in the Scripting API specification.

**Comment by zolkis** [comment]
IMHO it would make sense to use "Consumed Thing" and "Exposed Thing" in the Architecture and TD documents as in prose and use ConsumedThing and ExposedThing in Scripting as class names.

However, we could also use ConsumedThing and ExposedThing everywhere. 

If I imagine to be an outsider without a historical baggage, I'd prefer "consumed Web Thing" (or simply "Web Thing") and "exposed Web Thing", or "Web Thing client" and "Web Thing server" with corresponding WebThingClient and WebThingServer scripting classes, even though in the WG parlance ConsumedThing and ExposedThing are more accurate.

**Comment by mmccool** [comment]
Zoltan, I am reading your comments as preferring my first option above, "Exposed Thing".  That is fine with me... a simple search-and-replace can take care of it.
Please do read my updated definitions in the Terminology section and let us know if you are ok with it.   My intention was to broaden the definition slightly but include the meaning of the original text.

**Comment by zolkis** [comment]
Looks good!

**Comment by mlagally** [comment]
I agree with Zoltan's first comment, i.e. not using CamelNotation in prose text.

**Comment by mlagally** [comment]
@mmccool The terminology updates are ok.

**Comment by mmccool** [comment]
OK.   Seems like we agree on getting rid of the camel notation and going with the two-word notation.   I am working on cleaning up section 9 now and will convert to that convention in that section.   When I finish that I'll create another PR that fixes this...

**Comment by mmccool** [comment]
I have fixed this in Section 9 via https://github.com/w3c/wot-architecture/pull/176
This PR does not fix it elsewhere though (in the interests of getting this done, I *could* add changes elsewhere to address this to the above PR, though...)

**Comment by mmccool** [comment]
PR https://github.com/w3c/wot-architecture/pull/176 now fixes this globally.
