### ISSUE TITLE
Discovery API

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#18]
A Discovery API is mentioned but not defined anywhere.   Do we have one, do we plan to standardize one, or are we just talking in the abstract?   It might be good to at least mention a few ways in which discovery could be implemented, how Thing Descriptions could be obtained, and so forth... even if these discussions are non-normative.

**Comment by knimura** [comment]
Abstracted discovery API is defined in Scripting API spec.

**Comment by mkovatsc** [comment]
The Discovery API is only abstract in the sense that implementation is lagging. It has been an integral part of the Scripting API from the beginning.
