### ISSUE TITLE
Section 6.2 seems Redundant (System Configuration)

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#180]
Section 6.2 (System Configurations) duplicates material that is discussed at the start of Section 10 (WoT Deployments).   Should we delete it, or is it necessary for the exposition?   Note: Section 10 does have a lot more detail, and 6.2 is higher level, so it is not completely redundant.

**Comment by mlagally** [comment]
Call on 4.4.:
Section 6.2 should be preserved, since it gives an overview of the direct and indirect interaction between things.
Section 6 should be reworded to distinguish between high level concepts and deployments in section 9

**Comment by mkovatsc** [comment]
#221 revised most of Section 6.

Section 6.7 is now intended to map the Thing/Consumer/Intermediary abstraction to system components and introduce the terms Servient, Exposed Thing, and Consumed Thing. It probably should also explain that Things can act as server or as client at the transport layer.

**Comment by mkovatsc** [comment]
@takuki provided #227 which updated the System Configurations text.
