### ISSUE TITLE
Add a definition of Proxy

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#182]
Since we have a definition of Digital Twin.  Definition should be consistent with discussion in 9.1.2.

**Comment by mlagally** [comment]
call on 4.4.:
Matsukura-san will provide a PR.

**Comment by mkovatsc** [comment]
On the conceptional level (Thing, Consumers), we now have Intermediaries.
See #221

**Comment by mkovatsc** [comment]
Please clarify if we still need "proxy".

**Comment by mlagally** [comment]
call on 25.4.:
Defer - let's incorporate the terminology updates from section 6 into the rest of the document first.

**Comment by mkovatsc** [comment]
See #293.
We do not need such a definition. I propose closing this issue.
