### ISSUE TITLE
Describe Server and Client at the section "6.2 WoT Architecture"

### ISSUE THREAD

**Issue by chachamimm** [w3c/wot-architecture#188]
I have two opinions.

1) WoT Server and Wot Client  are described At the section "6.2 WoT Architecture". And Server and  Client are not described. But Server and Client is described at Fig 16 and Fig 17. I can't understand the reason why Server and Client is described. I think that these should be used the same terminology "WoT Server" and "WoT Client".

2) And I think that the relation of "Server" and "Client" is different in IoT and Internet. Basically in Internet Server is the global network, and Client is the local network. But in IoT Server is the local network, Client is the global network.  I think that WoT members are able to understand it, but other member may mot be able to understand. I think that "Server" and "Client" should be described in detail.

**Comment by mkovatsc** [comment]
6.1 no also rededines Servient and confuses it with an intermediary.

**Comment by mlagally** [comment]
Call on 4.4.:
Agree to talk about "server" and "client"-roles. We should not consider the location on the network or the size of the node as a indication, who is client or server.
We will have improved language as part of issue https://github.com/w3c/wot-architecture/issues/180

**Comment by takuki** [comment]
> Call on 4.4.:
> Agree to talk about "server" and "client"-roles. We should not consider the location on the network or the size of the node as a indication, who is client or server.
> We will have improved language as part of issue #180

Sorry that I could not join Architecture call. The time slot is very challenging for me.

I am a bit lost. In my opinion, Section 6.1 and 6.2 do not appear to talk about location on the network.

**Comment by mlagally** [comment]
@takuki Sorry about the confusion. The note should be:

Agree to talk about "server" and "client"-roles in __summary section 4.3__. We should not consider the location on the network or the size of the node as a indication, who is client or server.
We will have improved language as part of issue #180

**Comment by mkovatsc** [comment]
We could resolve this be adjusting the terminology again, so that we have:

* Things (they provide affordances described by TD)
* Consumers (instead of WoT Clients, as in some deployments they might be implemented in server role, where Things register and push data)

I think this should be possible, as I don't have the feeling we actually used "WoT Client" and "Wot Server" much in our groups. "Proxies" still fit this terminology.

The section on WoT Deployments would then give the examples where client and server roles from a protocol perspective come in.

**Comment by mmccool** [comment]
I would vote against renaming "clients" to "consumers".   For one thing, there is no symmetric renaming of "server".   For another, it's confusing to someone who understands client/server architecture and wants to see how it applies here.   If, however, you want to define a NEW concept, that *might* be ok... but if Consumers are defined as "consumers" of data then we would also want "sources".   I personally don't think it adds much and would be potentially confusing, so unless there is a really good reason.

I just think we have to be clear that devices/services can perform the client or server role, or both, from anywhere in the network.   We already tried to do that, but got it wrong in a few places, or overlooked a few things.   Let's just clean those places up.

**Comment by mmccool** [comment]
Some explicit counter-examples to server-in-the-cloud would go a long way towards making this clearer.

**Comment by mlagally** [comment]
Call on 11.4.:
Proposal:

Terminology: 
* WoT Clients will be renamed to Consumers
* Drop WoT Server 

*Move current section 6.2 to 6.11. 

Section 6.2
* new will be a decription of the abstract concepts, i.e. talk about things, consumers of things and intermediaries

Section 6.11:
* will describe the mapping of abstract concepts of section 6.2 to system components.
* Components are servients, i.e. they do not describe the roles at this level.
* Client and server terms should be replaced by servient both in the text and the figures.
* Needs to introduce the terms "exposed thing", "consumed thing" and "servient"

**Comment by mlagally** [comment]
Resolution in call on 11.4.
Accepted by all participants.

**Comment by mkovatsc** [comment]
When I started the work, I came to the conclusion that the "decription of the abstract concepts, i.e. talk about things, consumers of things and intermediaries" fits well under 6.1 Overview.

Hence, there is no 6.11, but 6.10 is now on "the mapping of abstract concepts of section 6.2 to system components".

**Comment by takuki** [comment]
Can @mlagally or @k-toumura -san. 

Can you please upload SVG files again? 
Please see https://github.com/takuki/wot-architecture/commit/6d9888baf091332d825992fb1cba679220c72880#commitcomment-33164305 .

**Comment by k-toumura** [comment]
@takuki, There are newer (but PPTX) files.
Please see https://github.com/takuki/wot-architecture/commit/6d9888baf091332d825992fb1cba679220c72880#commitcomment-33165156.

**Comment by mlagally** [comment]
@takuki @k-toumura Thanks for identifying this problem, I don't know what exactly happened.
I had a look at the latest version of the pptx file and it looks good to me.
@k-toumura Can you please create a PR which restores these two svg files.

**Comment by k-toumura** [comment]
@mlagally I made a PR for https://github.com/w3c/wot-architecture/issues/188#issuecomment-483168647.

**Comment by mkovatsc** [comment]
Wording with "client/server" eliminated in Section 6 through #221.
