### ISSUE TITLE
Architecture > WoT Servient Architecture

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#19]
The document as written seems to equate overall architecture with the internal architecture of the WoT Servient.   I think these are different levels of description and I think we need to make to make it clearer that a WoT system may, in fact, not use the internal architecture of the WoT servient shown.

I think we need a "Network Architecture" section and a "Servient Architecture" section.   The "Integration Patterns" section brought up by Matthias and some discussion of how you discover Things and get their Thing descriptions (or expose your own) could go in the Network section, as well as a general discussion of some other related issues (NAT traversal, CAs/HTTPS/offline use, local vs. global access, Discovery...)

**Comment by knimura** [comment]
It might not fit to your expectation because it does not include any network level considerations, but I was trying to explain abstracted connection of the servients in "primer for scripting API" doc.

https://w3c.github.io/wot-scripting-api/primer

**Comment by mmccool** [comment]
So it's a question of scope.  As a general deliverable, and based on the title of the document, I would expect it to discuss the entire WoT architecture, not just the Servient.   So either (a) the title should change to reflect the narrow scope ("WoT Servient Architecture") or (b) the scope should be broadened to include the Network Architecture as well.

I vote for (b).

**Comment by zolkis** [comment]
I'd also vote for (b).

**Comment by mkovatsc** [comment]
I just noticed that someone broke the sectioning, so that "4. General Description of WoT Servient" became the parent section for all following sections. This is of course wrong and gives the document the wrong spin that was not there before it was broken.

**Comment by mkovatsc** [comment]
See #23 for fix
