### ISSUE TITLE
Form definition fixes

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#198]
* "Extension operation type names" --> "Extension operation types"
* "Operation Name" --> "Operation Type"?
* Add Thing-level operation type "Names"
* Absolute URI --> IRI for extension types?

**Comment by mlagally** [comment]
Call on 4.4.:
Forms are defined based on web-linking definitions in RFC 8288.
This is an alignment with the CorAL specification.

**Comment by mkovatsc** [comment]
Also fixed in #221

**Comment by mkovatsc** [comment]
Fixed by merging #221
