### ISSUE TITLE
validate all references

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#200]

**Comment by mlagally** [comment]
Please update references to notes to a specific dated version.

**Comment by ashimura** [comment]
I've checked all the reference links and confirmed all of them were reachable and correct. I'll update some of them (for W3C TR docs) with the latest dated URIs when we publish the Architecture spec.

**Comment by mlagally** [comment]
Check again by PR transition.

**Comment by mmccool** [comment]
Kaz will do this as part of the PR publication, so we will change the label to "by PR publication".
