### ISSUE TITLE
"WoT network components" in abstract is not immediately clear

### ISSUE THREAD

**Issue by takuki** [w3c/wot-architecture#205]
In the abstract, there is a phrase "WoT network components" which is not immediately clear.

I suggest to define a term "WoT components" by extracting some content from section 5.2.1 as follows.

"WoT network components"
Network components such as devices, applications, proxies (i.e. gateways and edge devices) and directories that consist a WoT network.

**Comment by mlagally** [comment]
Call on 25.4.:
This simplifies IoT application development and enables portability across vendors and **devices**.
