### ISSUE TITLE
Relationship between academic project and W3C WoT is not clear

### ISSUE THREAD

**Issue by takuki** [w3c/wot-architecture#206]
In Introduction, there is a mention to academic project in 2010. 

It is not clear at all how it relates to W3C WoT. 
At least I have never heard of it.

I suggest to drop mention to the academic project, or make it clear how it relates to W3C WoT.

**Comment by mlagally** [comment]
Call on 25.4:
Remove the historical information.

The goals of the Web of Things are to improve the interoperability and usability of the Internet of Things (IoT). Through a collaboration involving many stakeholders over the past years, several building blocks have been identified that address these challenges.
The first set of WoT building blocks are now being standardized:

- the Web of Things (WoT) Thing Description [wot-thing-description],
- the Web of Things (WoT) Binding Templates [wot-binding-templates], and
- the Web of Things (WoT) Scripting API [wot-scripting-api].
