### ISSUE TITLE
Update Wikipedia page on WoT

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#207]
The Wikipedia entry on WoT is outdated and should reflect the work that happened over the last few years. 
https://en.wikipedia.org/wiki/Web_of_Things

**Comment by mmccool** [comment]
Should discuss with others (eg Dominique, etc.) at the workshop who have an interest, to accurately capture the history and the influences, and avoid bias.

**Comment by mkovatsc** [comment]
We actually did discuss during the workshop. The plan is as follows:

* Collect a list of evolution steps and/or flavors of the Web of Things and get consensus
* Write new paragraphs that reflect all agreed on flavors, while nobody should write their own section
* French version of the wiki article is said to be a good resource for inspiration, as it was apparently written by an independent party

@domguinard, @smnmyr, @andreiciortea would help -- Andrei, is this the right account?
We can get some more people from the academic community on board, I guess, e.g., @mblackstock

**Comment by mlagally** [comment]
I think we should work in github first to get text that's acceptable for all, 
before we perform the actual Wikipedia update.

We could start with the english version and, when finished / agreed, 
update the other language versions and apply the changes to Wikipedia.

For this purpose I have created a clone of today's english Wikipedia entry:
https://github.com/w3c/wot/blob/master/MARKETING/Wikipedia/english.md

**Comment by smnmyr** [comment]
Agreed, Mike! Let's keep it under the radar at this point :-)

**Comment by mlagally** [comment]
The english Wikipedia article has a lot of historic information and seems to end in 2014.
The historic information and acknowledgements should be preserved, however we need to provide up-to-date information.

An automatic translated version of the french version is at: https://translate.google.com/translate?sl=fr&tl=en&u=https%3A%2F%2Ffr.wikipedia.org%2Fwiki%2FWeb_des_objets
This is extensive and contains a lot of general information, however also doesn't not refer the W3C Web of Things work in any way.
It can help as a guidance on the structure of the article though.

**Comment by egekorkan** [comment]
I would suggest to have any further comment on https://github.com/w3c/wot-marketing/issues/4

**Comment by mlagally** [comment]
closing the issue here, since it will be handled in the marketing TF.
