### ISSUE TITLE
Section 8.10.2 Existing Device Described with a Thing Description is too restrictive

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#209]
"8.10.2 Existing Device Described with a Thing Description" contains the following sentence:

It is also possible to support existing IoT devices or services in the WoT and integrate them with other WoT Things by writing a Thing Description for them. __This can only be done however if the target device is using protocols eligible for WoT Protocol Bindings.__

This is too restrictive and limits the usefulness of WoT. It is possible to define protocol bindings for new protocols, the system is extensible. It is also possible to use a device from WoT by creating a protocol adapter on a gateway / proxy.

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-architecture/pull/273

**Comment by mkovatsc** [comment]
Was merged via CR-candidate-1.
