### ISSUE TITLE
Fix Terminology: NAT -> (NAT-) Proxy

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#212]
9.1.3 Devices in a Local Network Controlled from a Cloud Service

In Smart Home use cases, devices (sensors and home appliances) connected to a home network are often monitored and, in some cases, also controlled by cloud services. There is usually a NAT between the home network to which the devices are connected and the cloud. The NAT translates IP addresses as well as often providing firewall services, which block connections selectively. The local devices and cloud services can only communicate with each other if the communication can successfully traverse the NAT.

NAT appears as a system component. Consider replacing with proxy or gateway.

**Comment by mlagally** [comment]
https://github.com/w3c/wot-architecture/pull/264

**Comment by mkovatsc** [comment]
Still says "NAT-gateway" instead of "NAT device".

**Comment by mlagally** [comment]
Fixed in https://github.com/w3c/wot-architecture/pull/295
