### ISSUE TITLE
Fix WoT Client Terminology

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#213]
WoT Client

An entity that can connect with a network interface described by a WoT Thing Description (i.e., consume a Thing). WoT Clients usually implement multiple Protocol Bindings. WoT Client is also used to refer to a Servient in client role only.

Proposed new language:

An entity that can connect with a network interface described by a WoT Thing Description (i.e., consume a Thing). WoT Clients may implement multiple Protocol Bindings.

**Comment by mlagally** [comment]
See: https://github.com/w3c/wot-architecture/issues/188

**Comment by mkovatsc** [comment]
See update in #221:

Consumer: 
An entity that can process the WoT Thing Description format and interact with Things (i.e., consume Things).

**Comment by mkovatsc** [comment]
I removed language about the network interface, as Consumers are at the same abstract level as Things.

**Comment by zolkis** [comment]
> I removed language about the network interface, as Consumers are at the same abstract level as Things.
 
That makes sense, a Thing can be locally consumed. 
However, it might still need a local network interface (even if emulated). That provides an isolation that may make generic sense in IoT. But we don't need to say it out loud in every definition.

**Comment by mkovatsc** [comment]
Section 6 is also fixed by https://github.com/w3c/wot-architecture/pull/221
