### ISSUE TITLE
Clarification of the term "behavior"

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#220]
@mmccool , the document says

> The behavior aspect of a Thing includes both lifecycle management (onboarding, updating, decommissioning, etc.) but also the operational behavior of the Thing, which can include both autonomous behavior and support for interactions.

Can you please explain the lifecycle management part of "behavior".

**Comment by mkovatsc** [comment]
Furthermore, I am confused about (i) "Interactions", which (ii) consist of two parts, one being part (iii) implementation of the behavior from above.

**Comment by mkovatsc** [comment]
Neither do I understand:

> Interactions have two parts, the
                interaction affordances which are presented externally,
                and the interaction implementation, which defines the
                actual behavior corresponding to the interaction.

Behavior was already under behavior ("support for interactions").

My WIP #221 made some changes, so that affordances and Interaction Affordance is defined before the Web Thing section. This should help to make it clearer.

**Comment by mmccool** [comment]
I've updated the figure in the PPT master to remove "Interaction Implementation" and make the other requested changes but have not updated the figures as it seems some other edits to these figures have gone on in parallel.   Also I did create a PR for the requested updates to Figures 21 and 22 but I suspect these will also need more work to be made consistent.

**Comment by mkovatsc** [comment]
I think with the simplifications in the figures and new statement

> The behavior aspect of a Thing includes both the autonomous behavior and the handlers for the Interaction Affordances.

we are good now.
