### ISSUE TITLE
Consistent diagrams

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#228]
Align the diagram styles across the document, make sure that all figures
in the use case sections have the same sizes, colors of the diagrams match etc.

**Comment by mlagally** [comment]
Check for accessibility, i.e. that diagrams are readable for color-blind people. 
Please also check the printed version.

**Comment by k-toumura** [comment]
Sure.  I found [a list of accessibility evaluation tool](https://www.w3.org/WAI/ER/tools/) by W3C WAI.
Please let me know if there are any other useful tool for check accessibility.
