### ISSUE TITLE
Update figure 21 and figure 22

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#232]
Changes:
- Add a 2nd dotted block to figure 21 and 22
- Label it "alternative language runtime"
- remove "interaction implementation"

**Comment by mmccool** [comment]
See PR https://github.com/w3c/wot-architecture/pull/244.   Unfortunately I suspect that at this point these updates are out of sync with other changes that are also in flight, e.g. changes to color schemes.

**Comment by mmccool** [comment]
Note that the figure numbering has changed.  Fig 21 is now Fig 27, fig 22 is now fig 28.

**Comment by mmccool** [comment]
Due to the edits done by Matthias this issue is now taken care of and this issue can be closed.
