### ISSUE TITLE
Revise "6.6.1 Hypermedia driven" section 

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#235]
Ambiguity vs binding is a component or part of the affordance.
Also cardinality 0 or more or 1 or more bindings.

Continue the discussion in next call.

**Comment by mkovatsc** [comment]
It has to be 1 or more. Otherwise it is not a proper affordance, as the control or "how" part is missing from it.

This does not affect templates, as templates are incomplete TDs, and hence have incomplete Interaction Affordances.

**Comment by mlagally** [comment]
The current spec has 1, however we need to consider the templates more deeply.

**Comment by mkovatsc** [comment]
Templates do not contain Protocol Bindings, as they are instance-specific.

**Comment by mkovatsc** [comment]
No `id`, `name`, and `forms` in Templates.
