### ISSUE TITLE
Thing proxies

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#26]
@draggett commented this in the terminology discussion (however, out of scope there, so moved here):

> Another addition would address the concept of republishing a thing, e.g. to expose a thing on a cloud server where the thing is a proxy for a thing exposed by a device or application hub behind a network firewall.

We currently have the concepts of synchronization and Management Thing in the Scripting API work. Since this is more an architectural issue, I propose that a section on how to proxy/mirror Things is added AFTER we published the FPWD.

**Comment by mmccool** [comment]
I think this is a "Usage Pattern" and there are several such patterns, many related to proxies: caching, privacy filtering, access control, etc.   In some of those patterns the proxy may not have exactly he same interface as the thing it is proxying....

I think it would be reasonable to publish another non-normative document somehow describing how WoT features can be used but they don't necessarily belong in the WG deliverables... UNLESS they are needed as a use case to motivate a specific feature, for instance if we wanted to provide built-in support for synchronization.  Even if we did so, I think it can wait until after the FPWD.

**Comment by mkovatsc** [comment]
In #27, Matsukura-san commented that he would like to see the synchronization issue addressed in the Architecture document. In principle, I agree, as it is connected to the technical details that should go under "Deployment Scenarios and Guidelines" (see #27).
Still: AFTER we published the FPWD.

**Comment by mkovatsc** [comment]
Nobody is interested, but we have Proxy Servients quite prominent now.
Closing.
