### ISSUE TITLE
High-level content of the document

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#27]
During my current iteration, I somewhat lost my understanding of what the document currently actually offers. There is a lot of good and valid information, yet it feels a bit like a heap rather than the guidance document it should be. There is a list defining the purpose in the introduction. However, I do not see it reflected in the sections or the content:

- a guideline to the mapping between functional architecture and physical devices configuration
> This (probably) corresponds to the "Mapping Variations" section at the end
- a description of the role and functionality of each logical module
> This is the Servient architecture and somewhat building block explanation
- a reference defining what should be standardized
> Do we need this here? We already have a charter.
- a set of requirements for a WoT implementation environment.
> Not sure what this means

## My proposal

I fear that also other readers might have trouble to understand the provided information. Please tell me, if it is only me! For my personal better understanding, I would propose the following outline, which would produce a corresponding list for the purpose of the document:

### Functional Requirements
The list of requirements addressed by the WoT Architecture. Ideally, the final document does not only state the requirements, but also summarizes how they are met.

### Integration Patterns
An overview of the different integration patterns and envisioned deployments. See #9 and our architecture [overview figure](http://w3c.github.io/wot/charters/wot-wg-2016-figure.png)

### WoT Building Blocks and Servient Architecture
An introduction to the WoT building blocks. The result of combing these is either a Thing (only TD) or a WoT Servient (also Protocol Bindings and optionally the Scripting API). I guess this should be understood before looking at the deployment scenarios.
### Deployment Scenarios
Implementation guidelines for the different deployment scenarios. The current Section 5 answers what kind of discovery is required and what interactions are possible (my interpretation of the "API" lists). Issue #24 proposes to add guidance on how to enable connectivity in each scenario.

### Functional Roles of Servients*

*Let's think about better titles.

I find "Mapping Variations" quite misleading and the focus on specific devices in the sub-section titles is confusing, too. I think the purpose of the current Section 6 is to show which functional roles a Servient could serve (e.g., simply as state-of-the-art implementation of a Thing, or as gateway, or as cloud proxy, etc.). . Please confirm my assumption about this purpose.

### Security Considerations
Space to note everything that has to be considered for a secure WoT deployment...

---

Please let me know if you agree with this, as I want to avoid rewriting to much without consensus.

**Comment by mryuichi** [comment]
I almost agree to Matthias-san. However I have some suggestions for your proposal.
(1) The use cases should be put before the "Functional Requirements" because the readers cannot understand why the requirements had been derived from WHAT. For the description of the use cases of the WoT, the capter "Deployment Scenario" gives us good texts for the use cases for the Architecture document.
(2) The relations between the Architecture doc. and the others should be described for the Abstract and the chapter "WoT Building Blocks and Servient Architecture". The description in the Abstruct is a guide for easy understanding for the readers. That in "WoT Bulding Blocks" is necessary to clarify the reference points between each Building Blocks. These reference points should show some requirements for the other deliverables such as Scripting API, Thing Description, and Protocol Binding.

## The revised version of the contents of Architecture document is below.

### 1. Introduction
### 2. Terminology
### 3. Use cases (and deployment scenario)
 The current text of Deployment Scenario should be moved here. This text will give us some requiremetnts for the WoT Servient and the Integration Patterns.
### 4. Functional requirements
### 5. WoT Building Blocks and Servient Architecture
 The reference points should be clarified here.
### 6. Integration Patterns and Functional Roles
### 7. Security Consideration
### 8. Other Issues (cannot be specifed at this moment)

**Comment by mkovatsc** [comment]
Thanks, Kajimoto-san, I understand your comments. I think it is mostly again terminology about what we mean behind the section titles. Let me give another iteration:

## 1. Introduction
Descriptive over prescriptive motiviation, semantic metadata and re-usable building blocks. Briefly explain connection to other documents.

## 2. Terminology
Based on https://github.com/w3c/wot-architecture/blob/master/terminology.md

## 3. Use Cases and Integration Patterns
Quick overview, far simpler than Deployment Scenarios. See [Integration Patterns](https://www.w3.org/Submission/wot-model/#web-things-integration-patterns) and [image](https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/06/wot_integration_patterns.png) (Issue #9) as well as our [architecture overview or summary](http://w3c.github.io/wot/charters/wot-wg-2016-figure.png).
This should clarify enough to understand the requirements.

## 4. Functional Requirements
Current Section 3.

## 5. WoT Building Blocks and Servient Architecture
Current Section 4 with detailed links to the other documents and the addition of a "WoT in the Web Browser" sub-section.

## 6. Deployment Scenarios and Guidelines
Current Section 5 with the addition of the connectivity discussion similar to "Discovery" and "API"/features (Issue #24). 

## 7. Functional Roles
Current Section 6 with more focus on the role rather than a particular device.

## 8. Security Considerations

**Comment by mryuichi** [comment]
Sorry, I'm not Kajimoto-san. I don't know whether he has the same opinion. :)

Thank you for giving us another iteration, Matthias-san. I found a small gap between you and me. I try to clarify this.
(1) Actual use cases should be given in the use cases section. These use cases shall derive an abstract architecture like [architecture overview or summary](http://w3c.github.io/wot/charters/wot-wg-2016-figure.png). The reason why this abstract architecture could be derived from these use cases is need to describe in the use cases section. From the next section, the discussion should be done based on this abstract architecture .
(2) In my understanding, the section 5 (WoT Building Block...) will describe the Servient architecture and the interface between each Building Blocks. the section 6 (Deployment Scenarios...) will do the  connectivity among Servients and the interface between them. Is this correct?
[Synchronization of WoT servients](https://www.w3.org/2017/05/wot-f2f/slides/Sync-WoT-Servient-170517.pdf) I presented in Osaka was intended to specify the interface inside the servient and between the Servients.

Anyway, we cannot know which structures of architecture document is the best unless most of the description will be given. Shall we start to update first based on your structure?

**Comment by mkovatsc** [comment]
Oops, so sorry! I had too much conditioning on who is discussing this document :)

(1) Okay, understood. I would then propose to have the quick overview comparable to the [EVRYTHNG](https://www.w3.org/Submission/wot-model/#web-things-integration-patterns) and [Mozilla](https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/06/wot_integration_patterns.png) integration patterns in the introduction. The Use Cases section would be roughly like [old Section 5](https://w3c.github.io/wot-architecture/#deployment-scenarios), yet with less technichal details (i.e., no talk about discovery, APIs, or connectivity). Maybe, it should also avoid already talking about Servients, but just name the functional roles (existing device, smart home hub / factory cell controller and line controller, cloud proxy, etc.).

(2) The Deployment Scenarios section would be similar to the [old Section 6](https://w3c.github.io/wot-architecture/#mapping-variations), but have the technical details on how discovery, connectivity, and APIs work. This would include the Synchronization topics (as it boils down to discovery, connectivity, and APIs).

## New iteration

### 1. Introduction
Descriptive over prescriptive motiviation, semantic metadata and re-usable building blocks (i.e., links to other documents). 
Quick overview of the possible integration patterns (Thing-to-Thing, edge hubs, cloud) like by [EVRYTHNG](https://www.w3.org/Submission/wot-model/#web-things-integration-patterns) and [Mozilla](https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/06/wot_integration_patterns.png).

### 2. Terminology
Based on https://github.com/w3c/wot-architecture/blob/master/terminology.md

### 3. Use Cases
Similar to  [old Section 5](https://w3c.github.io/wot-architecture/#deployment-scenarios), but without technical soluations nor Servient terminology.
Conclude in [abstract architecture](http://w3c.github.io/wot/charters/wot-wg-2016-figure.png) that is independent from the application domains given in the use cases (home, factory, car).

### 4. Functional Requirements
Similar to [old Section 3](https://w3c.github.io/wot-architecture/#requirements-for-functional-architecture)

### 5. WoT Servient Architecture
Similar to [old Section 4](https://w3c.github.io/wot-architecture/#general-description-of-wot-servient) with detailed links to the other documents and the addition of a "WoT in the Web Browser" sub-section.

### 6. WoT Deployment Scenarios and Guidelines
Similar to  [old Section 6](https://w3c.github.io/wot-architecture/#mapping-variations) with focus on functional roles instead of devices and with technical detail on discovery, connectivity, and APIs. 

### 8. Security Considerations

**Comment by mryuichi** [comment]
Thanks, Matthias-san. I agree to this.

**Comment by Kazuo-Kajimoto** [comment]
Thank you Mathias-san, I also agree this.

**Comment by mkovatsc** [comment]
Okay, great. I will then apply this to the document.

**Comment by mmccool** [comment]
I also agree with the revision to the structure.  We probably also want to revisit the abstract to make sure it is in alignment with this structure and scope.  As the abstract of this document is probably the very first thing someone interested in the WoT will read I think it is important it cover things described in the charter even if it seems a little redundant (to us).

There is also some general material around security over in the TD draft which I think might make more sense in the Architecture document (for instance, threat models and scope, recommendations around scure development and deployment, general privacy considerations, etc).  I will put this on the agenda to discuss in the security TF.
