### ISSUE TITLE
Remove other scripting language environments from the WoT scripting API section

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#277]
Make clear that this is only ECMA-script:

> The WoT Scripting API is an optional "convenience" building block in WoT that eases IoT application development and is implemented using a Scripting Runtime (such as a Python, Lua or ECMAScript implementation) that is used in combination with a WoT Runtime. The WoT Scripting API enables writing WoT applications by user-defined scripts.

**Comment by mkovatsc** [comment]
See PR #291

**Comment by zolkis** [comment]
The question is should it be set in stone there could be only ECMAScript API?
In the group's past opinion no, there can be other APIs as well.
What about just saying the current implementation and non-normative standard API are ECMAScript, without ruling out other possibilities?

**Comment by mkovatsc** [comment]
We are referring to your document, which explicitly defines an ECMAScript API. "WoT Scripting API" is ECMAScript, but we leave plenty of room to allow for any possible API.
