### ISSUE TITLE
update section: 8.9.2 Existing Device Described with a Thing Description

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#279]
Remove:
Providing a Thing Description for a device also only allows it to be used in a server role, with its Thing Description being consumed by other Things. Using such a device as a Consumer will only in general be possible if the device can be modified to consume Thing Descriptions.

**Comment by mmccool** [comment]
Resolved in PR https://github.com/w3c/wot-architecture/pull/289.
