### ISSUE TITLE
"resolve merge conflict" commit reverted figure updates

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#294]
https://github.com/w3c/wot-architecture/commit/d0830d412d87a3aedd4dd33ee5c5c96655e8ba67#diff-926b3e11e68ce0c745adbabc2ec44666

broke the updated figures.

**Comment by mkovatsc** [comment]
This now affected https://github.com/w3c/wot-architecture/pull/296

**Comment by mlagally** [comment]
https://github.com/w3c/wot-architecture/pull/297

**Comment by mkovatsc** [comment]
@k-toumura , please close if you are now based on the latest figures.

**Comment by k-toumura** [comment]
Close this issue because I'm already based on the latest figures.
