### ISSUE TITLE
Accessibility review of figures

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#314]
Ask an accessibility expert for review of the arch diagrams.

**Comment by mkovatsc** [comment]
Just to share this link, which I found useful:
https://www.color-blindness.com/coblis-color-blindness-simulator/

**Comment by ashimura** [comment]
I've asked the accessibility experts to review the diagrams and am waiting their response.

**Comment by mmccool** [comment]
Should just be changing colors and fonts, so will be editorial.

**Comment by mlagally** [comment]
start via email thread towards a PR for Arch call on 23.5.
invite Josh O' Connor to next week's arch call

**Comment by mlagally** [comment]
Colour changes are addressed in 
https://github.com/w3c/wot-architecture/pull/358
There are still different white space margins in the diagrams.
@k-toumura, can you please regenerate the images?
