### ISSUE TITLE
Remove "Scripting Runtime" from Terminology section

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#320]
The PR for Issue https://github.com/w3c/wot-architecture/issues/278 did not remove the term "Scripting Runtime" from the terminology section.

Since this term is overlapping with WoT Runtime and Wot Scripting API, we should remove it completely.

@mkovatsc You owned issue 278 - can you please take another look?

**Comment by mkovatsc** [comment]
It did. Probably another wrong merge order into the candidate...

**Comment by mkovatsc** [comment]
Currently not in CR-candidate3 at least. Closing.
