### ISSUE TITLE
WoT Security and Privacy Considerations vs Guidelines

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#323]
I only now realize that the wot-security document was named "WoT Security and Privacy Considerations". We already have considerations in every specification. To me, that document was always more then considerations, namely cross-cutting guidelines that hence are a building block for W3C WoT.

How do others see this?
@mmccool is there any reasoning behind the title choice?

I would like to title the specification and building block "Web of Things (WoT) Security and Privacy Guidelines". The heading of 7.4 is on my side ;)

**Comment by mmccool** [comment]
My opinion is that this is an editorial change and can be discussed post-CR.

**Comment by mlagally** [comment]
@mmccool : Please confirm that the title will be changed by PR transition and re-published

**Comment by mmccool** [comment]
Yes, we can do that, as long as it is actually possible.   I will discuss with Kaz.   I guess in the worst case we could publish a completely new Note.

**Comment by mlagally** [comment]
See https://github.com/w3c/wot-architecture/pull/355

**Comment by mlagally** [comment]
Call on 23.5.:
Security Task Force had a discussion, will be continued in the main call.
Holding off the PR until this is resolved.

**Comment by mmccool** [comment]
This looks fine, please just go ahead and merge the above PR.

**Comment by mlagally** [comment]
I merged the PR
