### ISSUE TITLE
Acknowledge all contributors

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#329]
We should acknowledge all contributors to the architecture spec directly in the spec.

**Comment by mkovatsc** [comment]
Mentioning of *Klaus Hartke is missing, who helped to define the Web form concept.
I hope this is editorial. I could quickly do this update.

**Comment by mkovatsc** [comment]
Was fixed by @mmccool when adding the changelog on behalf of the the WoT Arch Editors.

**Comment by mkovatsc** [comment]
Let's keep it open in case our currently rotten brains forgot someone. Sorry for that in advance!

**Comment by mlagally** [comment]
See: https://github.com/w3c/wot-architecture/pull/354

**Comment by mlagally** [comment]
Add Daniel Peintner, Dominique Guinard

**Comment by takuki** [comment]
Joerg (Joerg Heuer) led the group for 2.5 years since the start (2014) to largely make the foundation of the current architecture.

I think Joerg deserves a special appreciation.

**Comment by mlagally** [comment]
See TD spec acknowledgement.

**Comment by mlagally** [comment]
Addressed in https://github.com/w3c/wot-architecture/pull/358
