### ISSUE TITLE
Read through CR-candidate-3 - minor issues

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-architecture#333]
I read through the CR-candidate-3 document (see https://cdn.staticaly.com/gh/w3c/wot-architecture/CR-candidate-3/index.html).

Please find below some comments.

I do not provide a PR since some are *real* mistakes while others are more a matter of taste and I leave it to the editors...

Hope this helps.

# General / Mixing 
* "serialised" vs "serialized" vs "serialization"
* "e.g." vs "e.g.,"
* "i.e." vs "i.e.,"

# Abstract

"the four intial WoT" --> "the four initial WoT"

# 3. Terminology

* Action: "dimm a lamp" --> "dim a lamp "

* Binding Templates: "The blueprints includes" --> "The blueprints include"

* Edge device: "a device which" --> "A device which"

* Hypermedia Control: "completeted" --> "completed"

# 4.1.1 Consumer

"Smart home can realizes added value" --> "Smart home can realize added value"

# 5.2.2 Devices

"using a descriptions of" --> "using a description of"

# 6.3 Web Thing

"concete messages" --> "concrete messages"

# 7.3 WoT Scripting API

Link to "[[?wot-scripting-api]" missing??

# 8. Servient Implementation

"As defined in ," --> link seems to be missing

"scripting languague" --> "scripting language"

# 8.2 WoT Runtime

"precicely" --> "precisely"

# 8.3 WoT Scripting API

"specificiation" --> specification"

**Comment by mkovatsc** [comment]
### Definition of Binding Tempaltes

to map Interactions to platform-specific messages  --> to map Interaction Affordances to

**Comment by mkovatsc** [comment]
See 3e7f1eaec296d0b769c1cb18f741f4bb06ebe003 and b373b3e09ccaa8d563c2f7794818d13abb5b0e30

**Comment by mkovatsc** [comment]
Still has "concete" and possibly other editorial issues.

**Comment by mlagally** [comment]
Let's collect all post CR issues in: 
https://github.com/w3c/wot-architecture/issues/350

**Comment by mlagally** [comment]
See https://github.com/w3c/wot-architecture/pull/354
