### ISSUE TITLE
TODO Fix Section 7

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#339]
Since there is now a CR-candidate4, I don't trust the merge overhead anymore. Please apply the following change:

The text after Figure 25 (the building block overview) is wrong and redundant. Please delete the paragraphs after the figure until the last one exclusive before Section 7.1,.

From:
> The WoT Thing Description (TD) contains metadata describing 
Until:
> In general it is considered a security best practice to explicitly manage 

Keep:
> In the following sections we will provide additional

**Comment by mkovatsc** [comment]
An improvement might be to explain the small boxes within the TD illustration in Section 7.1. Text snippets could be harvested from the deleted text.

**Comment by mlagally** [comment]
CR-candidate-4 will include all changes from the recent PRs that came in after CR-candidate-3 has been approved by the group.
I will merge all new PRs into it, so we have a combined version for review in our call in now +7:35 mins.

**Comment by mkovatsc** [comment]
The problem is that such an extremely moving target causes always new conflicts, which is in my opinion why we had these merge issues in the past. Will not touch it until it is clear how many Commits will be in between the fix and the merge...

**Comment by mlagally** [comment]
Approved in Chairs call on 9.5.
