### ISSUE TITLE
Post CR editorial fixes

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#350]
This is a bucket to collect all typos and other minor editorial changes.
Please add any mistakes you hit.

**Comment by mlagally** [comment]
Fix capitalisation in Terminology section
https://github.com/w3c/wot-architecture/pull/360

**Comment by mlagally** [comment]
Fix headline capitalisation: https://github.com/w3c/wot-architecture/pull/361

**Comment by mlagally** [comment]
Spellcheck changes: https://github.com/w3c/wot-architecture/pull/362

**Comment by mmccool** [comment]
All typos that have been noticed up to now have been fixed, and will will proceed to PR publication.  However, I will leave the issue open for additional fixes in the next version.
