### ISSUE TITLE
Broken internal reference

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#356]
[Section 4.1.14.2](https://w3c.github.io/wot-architecture/#sec-technical-requirements) has a broken reference `#sec-common-usecase-patterns`.

**Comment by mkovatsc** [comment]
Oh, line 844 is missing quotes: `class="wot-arch-diagram" alt="connected car use case />`

**Comment by mkovatsc** [comment]
I fixed it directly in master to minimize the time we have a broken Editors' Draft, as this also killed the main section to be recognized by ReSpec.

**Comment by mkovatsc** [comment]
048b832

**Comment by mlagally** [comment]
@mkovatsc Thanks Matthias.
