### ISSUE TITLE
How does one connect "directly to the cloud"?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/wot-architecture#364]
Section 4.1.1:

> Gateways can be connected to the cloud through the internet, while some appliances can be connected to the cloud directly.

What does it mean to be connected "directly" the the cloud and how is that different from connecting "through the internet"?

**Comment by mkovatsc** [comment]
Many IoT devices need a local gateway to which they connect and which provides "indirect" connection to the cloud. This must be done for any non-IP device, but is sometimes also done for IP-based devices.

Directly means the IoT device opens a direct connection to an endpoint in the cloud without any intermediary.

In the IoT context, but also Internet technology in general, gateway is a very common term.

**Comment by mlagally** [comment]
Arch call on Oct 20th:
Agreed to close
