### ISSUE TITLE
General TL;DR problem

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#366]
When receiving feedback, we often hear that people struggle to find a good way into our documents. Adding even more text to explain the structure would be counter-productive.

I can fully understand this, as I am not a fan of long texts either.

I would like to revise the abstract so that it is a concise statement about the document and resembles a short elevator pitch. I would move the excess text to the introduction.

**Comment by mlagally** [comment]
@mkovatsc The explainer document was written for this purpose - We could probably consolidate & compress to improve the abstract. Hat do you mean with the label "CR period"?

**Comment by mkovatsc** [comment]
> Hat do you mean with the label "CR period"?

We have to have a log of the comments received during CR period. Since we use GitHub and not some manual document, I introduced that label (see also [report](https://w3c.github.io/wot-thing-description/testing/report.html#cr_work))

**Comment by mkovatsc** [comment]
I don't think the explainer document has any reach beyond TAG review. It does not help the general audience. Note that the "abstract" is even longer than the introduction.

**Comment by mmccool** [comment]
I agree, the abstract should be short and to the point.  Certainly it should be shorter than the introduction (and the latter should not unnecessarily repeat information in the abstract). At the same time, we should avoid "marketing fluff" ("combating fragmentation", etc.) and just state clearly what the given spec is for ("provide metadata including a description of the network interface provided by an IoT device").

**Comment by mlagally** [comment]
This is addressed in issue
https://github.com/w3c/wot-architecture/issues/391
with 
https://github.com/w3c/wot-architecture/pull/397
