### ISSUE TITLE
General issues for FPWD

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-architecture#37]
After a first read through I would like to share my comments (mostly typos) below. The section I refer to are linked first.

**A**
https://w3c.github.io/wot-architecture/#introduction

Why is the Architecture document labeled as "the WoT Thing Description (this document)"?
Is it because of the four items in scope in the charter 

(https://www.w3.org/2016/12/wot-wg-2016.html).

If so.. we miss in the Arch Document Introduction any mentioning about  "Security and Privacy". Somehow the current form of the bullet list item confuses me a bit.

**B**
https://w3c.github.io/wot-architecture/#introduction

typo: 2nd last bullet lits item
"a guideline to map the abstract architechture ..."
vs 
"a guideline to map the abstract architecture ..."

**C**
https://w3c.github.io/wot-architecture/#sec-building-blocks

"This section presents the abstract architecture for the Web of Things, which is derived from the use cases in section <LINK> and the requirements in  section <LINK>,"

--> the reference to this sections seems to be missing

"Figure Figure 9 Abstract Architecture of W3C WoT summarizes "

Figure duplicated.

"Figure Figure 10 Conceptional Architecture of the WoT Building Blocks ..."

Figure duplicated again.

**D**
https://w3c.github.io/wot-architecture/#thing
"... ergo, everthing that has a Thing Description is a Thing. "
--> last para of 5.1
--> "everthing" ---> "everything"

**E**
https://w3c.github.io/wot-architecture/#wot-binding-templates

After Figure 11 ... "Figure" is duplicated again.

"Figure Figure 11 From Binding Templates to Protocol Bindings shows ..."

**F**
https://w3c.github.io/wot-architecture/#wot-scripting-api

"The WoT Scripting API as an optional building"
-->
"The WoT Scripting API is an optional building"

**G**
https://w3c.github.io/wot-architecture/#security-and-privacy-0

"Security is a cross-cutting issue that needs to be taken into account in all WoT building block .."

I think it should read "blocks" 

**H**
https://w3c.github.io/wot-architecture/#security-and-privacy-0

Still first para
"from Web secrutiy,"
to
from Web security,

**I**
https://w3c.github.io/wot-architecture/#wot-servient-architecture

First para
"Thus, the can be in both,"
to
"Thus, they can be in both,"

second para
"The previous Figure Figure 10 Conceptional Architecture of the WoT Building Blocks"
or
"Figure Figure 12 Implementation View of a Servient."

2 times figure again.

**J**
https://w3c.github.io/wot-architecture/#application
"The security metadata also needs to unclude"
cs
"The security metadata also needs to include"

and
"or certifictes "
vs
"or certificates "

**K**
https://w3c.github.io/wot-architecture/#scripting-api

The text is the same as in 6.1 with the same errors.
Besides I wonder whether we can do better than duplicating the same text.

**L**
https://w3c.github.io/wot-architecture/#protocol-bindings
end of 2nd para
"across theses generic protocol stacks. "
vs
"across these generic protocol stacks. "

**M**
https://w3c.github.io/wot-architecture/#servient

"Figure 14 Servient Consuming Thing the basic scenario"

The sentence seems to miss something like

"Figure 14 Servient Consuming Thing shows the basic scenario"

**O**
https://w3c.github.io/wot-architecture/#conclusion

"It is based on three building blocks ..."

I am not sure if the number is correct or how to count the building blocks given that Scripting is optional. What about Security?

**Comment by mkovatsc** [comment]
Thanks for your review!
I fixed all issues raised.
