### ISSUE TITLE
Review scripting API section wrt. TAG comment

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#370]
David Baron:
Another concern here is the references to the scripting API which appears to be optional and (as I understand it) lacks implementor interest. It seems like if it's not going to become a part of the architecture, it would be better to acknowledge that reality.

**Comment by danielpeintner** [comment]
While I agree that the current focus of the group was mainly on the Thing Description I also think that keeping Scripting API mentioned (as an _optional_ building block) in the architecture document is important.

It strongly believe that a **common** scripting facilitates deployment and specifically makes it much easier for new communities to explore our work.

**Comment by mlagally** [comment]
@danielpeintner I completely agree with your comment and think, that we should just double-check the corresponding section in the architecture spec, and perhaps have to add a clarification.

**Comment by danielpeintner** [comment]
I checked the document and besides some basic references / mentioning in 

- `Abstract`
- `1. Introduction` and 
- `3. Terminology`

the "Scripting API" appears in the following sections

- `7.3 WoT Scripting API`  (WoT Building Blocks)
- `8.3 WoT Scripting API` (Servient Implementation)
- `8.8 Alternative Servient and WoT Implementations`
- `10.2 WoT Scripting API Security and Privacy Risks`

and is clearly stated as **optional** and sometimes used as a possible example.

Hence, I do not really know what we could add to clarify that Scripting API is optional for the time being.

**Comment by mlagally** [comment]
After checking the document occurrences of the scripting API in the Arch call on 11.7. we agreed to Daniel's analysis. There is no need to change the current spec language wrt. scripting API optionality.
