### ISSUE TITLE
Where did w3c-wot-td-context.jsonld and w3c-wot-common-context.jsonld go?

### ISSUE THREAD

**Issue by onovo1** [w3c/wot-architecture#374]
It seems that the links to the w3c-wot-td-context.jsonld and w3c-wot-common-context.jsonld are broken. According to examples 16 and 17 of the document should be here:

https://w3c.github.io/wot/w3c-wot-td-context.jsonld,
https://w3c.github.io/wot/w3c-wot-common-context.jsonld

Where can I find those documents now?

I could find them both in the github folder: https://github.com/w3c/wot/blob/master/thing-description/
Is that the right location now?

Thank you!

**Comment by danielpeintner** [comment]
The `@context` namespaces have changed (e.g., to `https://www.w3.org/2019/wot/td/v1`) in the latest thing description updates. You ma want to look at https://w3c.github.io/wot-thing-description/#namespaces.

FYI: The files should be retrievable also online, see https://www.w3.org/2019/wot/td/v1

**Comment by mlagally** [comment]
@onovo1 
Where did you find the originating links to these two files?
The two context files you refer to are not part of the current architecture specification.

**Comment by onovo1** [comment]
Thank you both for your answers.

I found the original links from the protocol binding template: https://www.w3.org/TR/wot-binding-templates/
Examples 16 and 17 of the document.

**Comment by onovo1** [comment]
According to https://w3c.github.io/wot-thing-description/#namespaces,  there are four namespaces: 
- Core (https://www.w3.org/2019/wot/td#)
- Data Schema (https://www.w3.org/2019/wot/json-schema#)
- Security (https://www.w3.org/2019/wot/security#)
- Hypermedia Controls (https://www.w3.org/2019/wot/hypermedia#)

Is there a way to get the raw data of these namespaces in JSON through an URL instead of an HTML webpage?
I am trying to parse the information of those namespaces.

Thanks!

**Comment by mlagally** [comment]
Please take a look at https://github.com/w3c/wot-thing-description/tree/master/context

@vcharpenay can you confirm?

**Comment by danielpeintner** [comment]
> Is there a way to get the raw data of these namespaces in JSON through an URL instead of an HTML webpage?

A simple GET https://www.w3.org/2019/wot/td/v1 should deliver you JSON content with content-type: application/ld+json

**Comment by onovo1** [comment]
> A simple GET https://www.w3.org/2019/wot/td/v1 should deliver you JSON content with content-type: application/ld+json

Right. https://www.w3.org/2019/wot/td/v1 delivers JSON content but unfortunately the other namespaces that I referred above (core, data schema, security and hypermedia controls) do not

**Comment by egekorkan** [comment]
It is now fixed in the protocol bindings document via https://github.com/w3c/wot-binding-templates/commit/ffbb382eb9362bb35f028db9097bb82ed43f0207

**Comment by onovo1** [comment]
> It is now fixed in the protocol bindings document via [w3c/wot-binding-templates@ffbb382](https://github.com/w3c/wot-binding-templates/commit/ffbb382eb9362bb35f028db9097bb82ed43f0207)

Sorry, what is exactly fixed in the Binding Templates Document? We were referring to the namespaces described in the Thing Description document. Right now, it is not possible to get a JSON document when retrieving the namespaces. At least, it is still returning an HTML document. It can be easily check sending a GET request:  curl -X GET https://www.w3.org/2019/wot/td#

**Comment by takuki** [comment]
Hi. Adding an option _--header "Accept: text/turtle"_ may help in getting a turtle representation.

**Comment by onovo1** [comment]
Thank you for your answer. 
I still think a JSON representation should be returned  since all the examples in the document are in JSON.

**Comment by mlagally** [comment]
@vcharpenay can you please take a look at the onology files and the comments from @onovo1 ?

The namespaces link to W3C specification documents, however there appears to be no way to obtain a JSON representation.

**Comment by vcharpenay** [comment]
Hi @onovo1,

what do you expect these JSON file to include? OWL definitions, JSON-LD context definitions, something else?

The four namespaces you mention are ontology namespaces: at the moment, they merely include vocabulary definitions, i.e. a list of terms. In a near future, they'll include more elaborate OWL axioms but they will never include JSON-LD context definitions.

Now, if you are indeed looking for vocabulary definitions, they are only served in Turtle. All RDF frameworks can process that format. If you want these definitions in JSON, you can try online converters (e.g. [here](https://rdf-translator.appspot.com/) and [there](https://rdf-translator.appspot.com/)), to get a JSON-LD document. Note, however, that you will _not_ get a context file but simply the namespace vocabulary definitions, in JSON(-LD).

Does that help?

**Comment by onovo1** [comment]
Hi  Vcharpenay,

Thank you for your explanation. As far as I understand, the Things Descriptions are, by default, encoded in JSON and JSON-LD. Thus, allowing their automatic processing.

I am implementing an automatic processing tool using the Thing Description and, somehow, it is very confusing that the different namespaces documents are retrieved in different contexts (JSON-LD, Turtle...). That complicates the implementation of an automated tool: first the tool needs to understand several contexts, then the tool needs to convert the contexts to a common format. I think all that complexity is unnecessary when one of the requirements of the WoT is to work smoothly in constrained devices.

I am fine with any solution, even though, IMHO the current solution is cumbersome. I would rather prefer JSON-LD documents with the proper context files for easy parsing and as a way of avoiding the implementation of converters tools in constrained devices. 

However, I think the chosen solution should be documented properly and right now, much of the information explained in this thread (which I really appreciate the effort dedicated by the community explaining me all my questions) are not explained properly in any of the documents. :(

**Comment by vcharpenay** [comment]
Note that the chosen solution is [standard practice in the Semantic Web community](http://wifo5-03.informatik.uni-mannheim.de/bizer/pub/LinkedDataTutorial/) and it complies to the Linked Data (LD) principles. A LD agent will fetch all pieces automatically, simply by following links embedded in RDF. [rdflib.js](https://github.com/linkeddata/rdflib.js) is a good JS implementation for that, for example; your only input is the TD's location on the Web.

That said, there is a PR in progress (w3c/wot-thing-description#744) to significantly extend the documentation of the different namespace. I can surely take your feedback into account. I am not sure I understand what you mean by "automatic processing", though. Does it mean fetching JSON-LD and Turtle files? Does it mean reasoning over the TD?

Could you explain in a bit more details your goal with retrieving namespace documents?

**Comment by mlagally** [comment]
Arch call on Oct 20th:
Agreed to close
