### ISSUE TITLE
definition of privacy is too weak

### ISSUE THREAD

**Issue by dbaron** [w3c/wot-architecture#375]
The [definition of privacy](https://w3c.github.io/wot-architecture/#dfn-privacy) (currently "The system should maintain the confidentiality of Personally Identifiable Information.") given seems far weaker than it should be.  A better definition seems like it should consider concerns over information that is not (on its own) PII, and should consider the risks of sharing information even when it is kept confidential.  It may be preferable to link to an existing definition elsewhere rather than writing your own.

A few examples of things that many people would consider aspects of privacy, and which might be observable through information from Web Things, but that I don't think fall under the current definition:
* whether a particular person (or some person within a particular residence) uses a particular type of medical device
* whether a particular person is currently at home, or whether their home is currently occupied
* what times a particular person typically is asleep and awake
* the current physical location of a person or a device

In all of these cases, the mapping of the IP address(es) or equivalent to a particular person's name seems like it would constitute PII, but I believe privacy should also include the sensitive things that are related to the IP address(es), even separate from the mapping to a person's name or identity, since the name or identity can often be linked in other ways.

**Comment by dbaron** [comment]
(This was originally part of https://github.com/w3ctag/design-reviews/issues/355#issuecomment-505228840 .)

**Comment by mlagally** [comment]
@dbaron Thanks very much for your comments. 

There was a discussion in the security TF which will imply a revision of the https://github.com/w3c/wot-architecture/pull/368
Please take a look at the discussion there.

When the revised PR is available, there will be a clear definition of privacy.

**Comment by mlagally** [comment]
Call on 22.8.: The PR https://github.com/w3c/wot-architecture/pull/368 needs to be updated to contain a definition.

**Comment by mlagally** [comment]
Arch call on 29.8.:

The definition should be aligned with the definition in
https://www.iso.org/obp/ui/#iso:std:iso-iec:29100:ed-1:v1:en

and contain a definition that is in accordance with the following terms:

# privacy controls
measures that treat privacy risks by reducing their likelihood or their consequences
Note 1 to entry: Privacy controls include organizational, physical and technical measures, e.g., policies, procedures, guidelines, legal contracts, management practices or organizational structures.
Note 2 to entry: Control is also used as a synonym for safeguard or countermeasure.

# privacy enhancing technology
PET
privacy control, consisting of information and communication technology (ICT) measures, products, or services that protect privacy by eliminating or reducing personally identifiable information (PII) or by preventing unnecessary and/or undesired processing of PII, all without losing the functionality of the ICT system
Note 1 to entry: Examples of PETs include, but are not limited to, anonymization and pseudonymization tools that eliminate, reduce, mask, or de-identify PII or that prevent unnecessary, unauthorized and/or undesirable processing of PII.
Note 2 to entry: Masking is the process of obscuring elements of PII.

# privacy policy
overall intention and direction, rules and commitment, as formally expressed by the personally identifiable information (PII) controller related to the processing of PII in a particular setting

# privacy preferences
specific choices made by a personally identifiable information (PII) principal about how their PII should be processed for a particular purpose

# privacy principles
set of shared values governing the privacy protection of personally identifiable information (PII) when processed in information and communication technology systems

# privacy risk
effect of uncertainty on privacy
Note 1 to entry: Risk is defined as the “effect of uncertainty on objectives” in ISO Guide 73 and ISO 31000.
Note 2 to entry: Uncertainty is the state, even partial, of deficiency of information related to, understanding or knowledge of, an event, its consequence, or likelihood.

# privacy risk assessment
overall process of risk identification, risk analysis and risk evaluation with regard to the processing of personally identifiable information (PII)
Note 1 to entry: This process is also known as a privacy impact assessment.

**Comment by mlagally** [comment]
Arch call on Aug 29th:

We decided to ask the PING experts for a recommendation:
https://github.com/w3cping/tracking-issues/issues/12

**Comment by mlagally** [comment]
resolved by replacing it with ISO definitions in call on Sept 12
