### ISSUE TITLE
definition of security is too weak

### ISSUE THREAD

**Issue by dbaron** [w3c/wot-architecture#376]
The [definition of security](https://w3c.github.io/wot-architecture/#dfn-security) (currently "The system should preserve its integrity and functionality even when subject to attack.") appears (although it's a bit unclear) not to include revealing private information as a failure of security.  Maintaining confidentiality of data that was intended to be kept confidential is generally considered part of security.  I suspect there are likely also other topics that were omitted but should be included.

It may be preferable to link to an external definition.

(This was originally part of https://github.com/w3ctag/design-reviews/issues/355#issuecomment-505228840 .)

**Comment by mlagally** [comment]
@dbaron Please take a look at the discussion in https://github.com/w3c/wot-architecture/pull/368

When the revised PR is available, there will be a clear definition of security.

**Comment by mlagally** [comment]
Call on 22.8.: The PR https://github.com/w3c/wot-architecture/pull/368 needs to be updated to contain a definition.

**Comment by mlagally** [comment]
Arch call on Aug 29th:

We decided to ask the PING experts for a recommendation:
https://github.com/w3cping/tracking-issues/issues/12

**Comment by mmccool** [comment]
See https://github.com/w3c/wot-architecture/pull/384.

**Comment by mlagally** [comment]
resolved iby replacing it with ISO definitions in call on Sept 12
