### ISSUE TITLE
broken reference in definition of Personally Identifiable Information (PII)

### ISSUE THREAD

**Issue by dbaron** [w3c/wot-architecture#377]
The [definition of Personally Identifiable Information (PII)](https://w3c.github.io/wot-architecture/#dfn-personally-identifiable-information) currently has a broken reference that appears as `[[!ISO/IEC 29100]]` but should instead be a link to something.

(It's also not clear to me if that document is freely available; if it's not, it may be preferable to link to an alternative source that is.)

(I got here from w3ctag/design-reviews#355.)

**Comment by mlagally** [comment]
@dbaron Thanks for flagging the broken reference.
I fixed it in the PR https://github.com/w3c/wot-architecture/pull/378.
We are using the same definition as ISO/IEC-29100 and include it verbatim in the definitions section.
I added a note to clarify.

**Comment by mlagally** [comment]
call on 22.8. We verified the change - closing the issue
