### ISSUE TITLE
Data Schema should be briefly explained in Architecture Document

### ISSUE THREAD

**Issue by takuki** [w3c/wot-architecture#382]
Currently, the term "Data Schema" is mentioned 4 times in the document.

However, the term is not explained anywhere in the document.

I would suggest to describe it in the terminology section.

**Comment by mlagally** [comment]
Data Schemas are used in a normative section (6.4.1) of the architecture spec and are also extensively used in the TD spec.
We need a definition in the terminology section. 

@takuki Can you please create this definition?
