### ISSUE TITLE
Add short mention of ID privacy risk to Architecture Security and Privacy Considerations

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#398]
Add a short mention of the ID risk to privacy in TDs to Arch doc (but refer to the TD spec for details).

Feedback from PLH: ...it would be better to mention the risk of "id" (esp. unique
  ID's being mandatory and we made it optional and removed the
  uniqueness) within the section 10...

**Comment by mlagally** [comment]
Arch call on 17.10.
The issue has been addressed by adding mitigations to section 10.
