### ISSUE TITLE
Must close IG architecture draft

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#4]
We still have two versions online: [WG Editor's Draft](https://w3c.github.io/wot-architecture/) and [IG draft](https://w3c.github.io/wot/architecture/).

I was thinking, we decided to release IG draft as an IG Note, no? Anyhow, we should replace https://w3c.github.io/wot/architecture/ (IG draft) with a commented link to the WG Editor's Draft, and potentially the "archived" IG Note.

**Comment by Kazuo-Kajimoto** [comment]
Sure, as IG document, https://w3c.github.io/wot/architecture/ shoud be closed as former IG discussion result.
Current WG document, https://github.com/w3c/wot-architecture should also be closed as WG for WoT V1.0, then next discussion on WoT architecture in IG will refer the latest this WG architecture document.

Then, anyone, could you tell me how should I declare
1) Close IG architecture document for former discussion
2) Close WG architecture document for WoT V1.0
3) Refer current WG architecture document for next discussion on IG for WoT V2.0 or later.

**Comment by mkovatsc** [comment]
@ashimura, can you help with the W3C process options?

I would say:

1. What happened to the Notes we prepared for publishing? Maybe IG Architecture still needs to be prepared for this. Anyhow, it should be archived through the IG Note process and the GitHub pages document changed to a disclaimer and links to the archive and the WG Editor's Draft on GitHub.
2. Here I expect an FPWD release to be versioned and archived.
3. Continue evolving the Editor's Draft on GitHub.

**Comment by mkovatsc** [comment]
I changed the title of the IG document to "Architectures for the Web of Things".

**Comment by mkovatsc** [comment]
Replaced IG draft with link to WG document.
