### ISSUE TITLE
Possible typos

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/wot-architecture#420]
Thank you for the useful specification.
I found some possible typos in the WoT Architecture Candidate Recommendation:

(1) Sec 6.7.2, in the third sentence - A period might be missing before "For example".
(2) Sec 6.7.2, in the last sentence - "The If necessary" might be "If necessary".
(3) Sec 7.3, in the third sentence - I wonder if the expression "supports enables" is correct.
(4) Sec 8.8.1, in the second sentence - A period might be missing before "Except for the latter".
(5) Sec 8.8.2, in the first sentence - A period might be missing before "Much of the previous discussion".
(6) Sec 9.1, in the third sentence - "indentifiable" might be "identifiable".
(7) Sec 10.3.2, in the Mitigation - "event better" might be "even better".

**Comment by mlagally** [comment]
Dear Kamitsuna-san,
many thanks for your careful reading and for reporting these typos.
All of your issues are real typos and I have created a PR with the fixes.
