### ISSUE TITLE
Arrow between App+Scripts and TD in Fig. 10

### ISSUE THREAD

**Issue by ToruKawaguchi** [w3c/wot-architecture#43]
In figure 10 (https://w3c.github.io/wot-architecture/#architecture-concept), 
three arrows are drawn from 1)"Application + WoT Scripting API", 2)"Interaction Model", 3)"WoT Binding Templates" to "WoT Thing Description". But I could not find what aspect of "Application + WoT Scripting API" is written in Thing Description. I'd like ask guidance about that, but in case if there is no particular entity in TD which corresponds to "Application and WoT Scripting API", I propose to remove that arrow from Fig. 10.

P.S. 
Are following words generally used in English specification?
looked like a little bit difficult to understand for us non-European readers.
- ergo (in 5.1) ->therefore?
- portmanteau (in 6) -> bag?

**Comment by mkovatsc** [comment]
The application is actually defining which Interactions are available (Properties, Actions, Events). I made the arrow also come from the whole Thing/Servient, as also global metadata such as location goes in the TD.

I can change ergo to therefore.

Portmanteau is a linguistic term for this word creation.

**Comment by ToruKawaguchi** [comment]
@mkovatsc Thanks. It became clear.
