### ISSUE TITLE
Give basic definition of "End-to-End Security"

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#430]
Consistent with "authentication", we would like to see a basic definition of the oft-used term "end-to-end security" in the Architecture document, since it may also be used in other places, eg Protocol Bindings.   However, detailed discussion of the topic will be place in the Security and Privacy document.

See issuehttps://github.com/w3c/wot-security/issues/144

**Comment by mlagally** [comment]
Call on 6.2.:
Need one or more use cases.

**Comment by mjkoster** [comment]
In the definition of "Endpoints" we can consider focusing on the roles we define in WoT architecture, which are servient-client and servient-server. We will also define the discovery endpoints and roles, perhaps consisting of the discovery service, registrant client, and discovering client, or analogous roles in a multicast system
