### ISSUE TITLE
Create terminology definition for "partial TD"

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#453]

**Comment by sebastiankb** [comment]
We should avoid to introduce another term such as "partial TD". What I understood so far by "partial TD" would fit into the TDT assumptions.

**Comment by zolkis** [comment]
I think we don't _need_ to define a formal `partial TD` term, but we could use it as a common language term, i.e. any subset of clauses from a TD.

**Comment by mlagally** [comment]
> We should avoid to introduce another term such as "partial TD". What I understood so far by "partial TD" would fit into the TDT assumptions.

A Thing Template according to the current definition has additional semantics, i.e. it is a partial TD or TD subset with a set of additional constraints such as mandatory vocabulary terms.

**Comment by sebastiankb** [comment]
@mlagally 
>with a set of additional constraints such as mandatory vocabulary terms.

For better understanding, could you give an example of what kind of mandatory vocabulary this could be?

**Comment by mlagally** [comment]
Proposal (Arch call on 2.4.): 
Partial TD = subset of a TD data model which doesn't not require all mandatory keywords of the TD.
A partial TD is used as a search pattern for discovery.

**Comment by mlagally** [comment]
Need a MR against the architecture spec.

**Comment by mlagally** [comment]
Agreed in the Arch call on Jan 14th:

Partial TD = 
subset of a TD information model which includes the root but doesn't not require all mandatory elements of the TD.
It is including only a subset of the terms of the TD information model.

A data model conformant to the Thing Description schema can be validated by validating the subset of elements that are present.

Note: When serialised a partial TD includes all outer elements of a TD but may omit internal elements.
A partial TD is used as for the scripting API for the creation of exposed things.

Todo: Christiano and Daniel to provide a link to the Scripting spec

---

TD Fragment = 
substructure of the data model of a TD.
It is a valid object structure  that can be validated syntactically against the TD datamodel defined in chapter 5 of the TD spec, however im may omit some context that allows full validation.

Note: In JSON represention it must be a valid JSON however could be just an inner structure omitting outer elements, curly braces etc. As a use case the TD fragment is useful for Discovery results returned by a JSON-Path query.

Todo: McCool to provide a link to the Discovery spec

**Comment by danielpeintner** [comment]
> Todo: Christiano and Daniel to provide a link to the Scripting spec

The scripting API [produce](https://w3c.github.io/wot-scripting-api/#the-produce-method) methods expects a td argument (which is essentially a partial TD).

**Comment by relu91** [comment]
For consistency, I'll link my comment about Partial TDs https://github.com/w3c/wot-architecture/issues/574#issuecomment-760214194. (sorry before today's calls I confused Partial TDs for Thing Description Fragments). 

>The scripting API produce methods expects a td argument (which is essentially a partial TD).

+1

**Comment by mmccool** [comment]
I think this PR addresses this (Partial TD is now in the spec).   TD Fragment also exists but has an ed note that probably needs to be cleaned up, is in the wrong order lexicographically, and I also personally think it should be TD Element" to be consistent with JSON.   So... probably we should close this issue (on Partial TD, now resolved) and create another one to clean up TD Fragment.
