### ISSUE TITLE
Smart Grid Use Case

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#460]
Review the smart grid use case section in:
https://cdn.statically.io/gh/w3c/wot/aa90b2b8/ucr-doc/index.html#domain-smart_grids

Identify gaps and new requirements with the current WoT building blocks
and document the findings / gaps in a requirements document.

**Comment by wiresio** [comment]
See PR https://github.com/w3c/wot-architecture/pull/487

**Comment by mlagally** [comment]
@wiresio has provided a UC.
Closing the issue.
