### ISSUE TITLE
Provide more information of the "Thing Directory"

### ISSUE THREAD

**Issue by onovo1** [w3c/wot-architecture#47]
Hi,

I think the Architecture document provides very little information about the "Thing Directory" module. Even, it doesn't reference the open source code in the github.
It would be nice to have a new section where it explains in more detail about this module. For instance, how the devices can located the "Thing Directory", uses cases, operations (TD registration, TD update, TD lookup...), examples...

Oscar

**Comment by mkovatsc** [comment]
The open-source code is not normative, and hence not a suitable reference. But indeed the missing discovery section in the Architecture Document is a bug that will be fixed in the next Working Draft release.

**Comment by onovo1** [comment]
Thanks Matthias. 
Is there any plans to advertise the open-source in other places? I think, right now, it is not advertise much and people is missing the opportunity of using it.

**Comment by relu91** [comment]
Hello,

I'm a phd student from the University of Bologna. My research topic covers the use of web of things technologies in SHM field. 

I'm also interested to know more about "Thing Directory" and the discovery process in general. In particular I would ask how the thing descriptor is registered using the _CoRE Resource Directory_ specification. 
Does the servient register it's base web endpoint? Or every WoT Interface endpoint? Or both? Or something else?
I suspect that the first is easiest and cleanest solution...

Finally is there a more appropriate place to ask this kind of questions?

Thank you,
Cristiano.

**Comment by mlagally** [comment]
Won't be addressed in the current WG charter.
