### ISSUE TITLE
Identifiers of virtual devices

### ISSUE THREAD

**Issue by auslavs** [w3c/wot-architecture#486]
From Section 5.2.4 Digital Twins

> Identifiers of virtual devices need to be newly assigned, therefore, are different from the original devices. This makes sure that virtual devices and the original devices are clearly recognized as separate entities.

I think that in _some_ cases Digital Twins should not be recognised as separate entities.
Take the case where the Digital Twin is an emulation of physical hardware, and you are using it to verify the functionality of some higher-level software. Ideally, the software under test should not know the difference between the real hardware and Digital Twin. 

The purpose of the test is to verify how it will perform in production, intentionally making these sub-systems distinct from each other in this scenario would undermine the test.
The Volkswagen emission scandal is a sinister example what could go wrong if these systems are uniquely identified.

**Comment by mlagally** [comment]
I'm not sure that a problem, that was caused by lack of proper testing coverage (i.e. not testing cars in a real driving situation but only in simulation scenarios) should be solved by a format specification.

In the thing description specification identifiers are optional, the same is true for digital twins. 

I agree that the software under test should not distinguish between a twin a a physical device, however this should be ensured by other means, i.e. quality control, proper test methodology, independent review, etc.

**Comment by mmccool** [comment]
I think it would in general be a bad idea to give different entities the same identifier.  It is likely to break assumptions of other systems like caches, and lead to confusion on networks where both devices are accessible, and/or an unfortunate dependence on things like network addresses (which should be a lower-level concern...) to distinguish them.  Instead a system should simply be configured to use the digital twin in place of the "raw" device.  We might, however, want to do things like have links (with appropriate relation types) in the TDs pointing from the digital twin to the raw device (and maybe vice-versa?).

Another thing to consider is the use of DID and DID documents.  You could have something like the DID document for the DID of the twin referring to both the digital twin and the raw device (again with different link relation types; a DID Document is basically a set of typed links).   But I'd still use different DIDs for the raw and twin devices.

**Comment by auslavs** [comment]
I think I misunderstood the purpose of the identifier and the context.

I imagined it was merely a device name rather than something that could incorporate a thing's location. Also, I assumed that test and production would be separate, which may not be relevant in the WoT.

I agree that other means of ensuring the software under test cannot distinguish between a thing and its digital twin such as the use of an intermediary, or using different testing methodology as previously mentioned would be more suitable.
