### ISSUE TITLE
Working Draft for Prague PlugFest

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#49]
This issue is to collect the topics that should be addressed for the next WoT Architecture Working Draft.

**Comment by mkovatsc** [comment]
### Use cases
* Came up again in the Mozilla/Evrythng discussion and existing use cases did not answer all questions
* We need “tangible” use cases such as “Actions provide result data”, “Properties have complex data”, “Invoked Actions must be monitorable”, …
* I would add these as bullet point lists in the sub-sub-sections that describe the scenarios (3.x.x)

**Comment by mkovatsc** [comment]
### Discovery
* Informatively describe the Thing Directory (also see https://github.com/w3c/wot-architecture/issues/47)
* Proxy issues for Directories discussed in last PlugFest (local vs global addresses in TD…)
* Outline other discovery methods (also see https://github.com/w3c/wot-architecture/issues/48)

**Comment by mkovatsc** [comment]
### Deployment Scenarios
* I still I don’t fully see the difference to Use Cases
* Can add findings from last PlugFest (proxies) to current sub-sections
* Describe more the role of TDs?
  * Feature Levels
    * TD as syntactic API description (Mozilla use case)
    * TD as semantic API description (making use of Linked Data annotations)
  * TD Usage Patterns
    * Describe device’s network-facing API --> used by direct client, gateway, or platform’s southbound API
    * Also simplifies gateway implementation by providing uniform API descriptions for heterogeneous platforms (data models / protocols)
    * Describe platform’s/service’s northbound API --> used by “global” clients (e.g., smartphone, browser)
    * To transport metadata (e.g., device/onboarding information) from device level to management service (e.g., fill knowledge base with triples)
  * How come TDs into existence
    * Existing device --> created by tool, hosted externally (e.g., describe an existing device that has no machine-readable information)
    * WoT-native device --> hosted on device (discovery?) What is the out-of-factory TD? Only config interfaces and metadata or also unconfigured, and hence non-working Interactions? Dynamically extend TD by device Servient after commissioning was done or static TD on device and enhanced on mirror?
    * Digital service such as cloud mirror --> dynamically serialized from service model (can be custom, can be knowledge base / triple store)

**Comment by ToruKawaguchi** [comment]
### Interaction Pattern
* Sorry if this is already discussed, but I would suggest to have a section describing interaction pattern, e.g.) For what the Property/Action/Event is used, how they works throughout system, etc. Thing Description Document already has explanations of each interaction pattern from metadata point of view, but since it is some kind of backbone throughout WoT system, describing it in Architecture document from system-wide aspect would make sense. 
* Adding a section to Chapter 5 might work, because the figure there has a box named "Interaction Model", without any explanation to that. 
* In addtion, it might be good to draw some example sequence diagrams, to illustrate how they work throughout system.

**Comment by mkovatsc** [comment]
Need to include lifecycle model.

**Comment by mkovatsc** [comment]
Use cases have been reworked and deployment scenarios are being rewritten by @mryuichi .

> I would suggest to have a section describing interaction pattern, e.g.) For what the Property/Action/Event is used, how they works throughout system, etc

Will be in https://w3c.github.io/wot-architecture/#interaction-model-0

> In addtion, it might be good to draw some example sequence diagrams, to illustrate how they work throughout system.

@ToruKawaguchi THanks for providing the sequence diagrams for the Architecture Document

Done.
