### ISSUE TITLE
Update Smart City use cases with Security and Privacy Considerations

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#492]
Update:
smartcity-*.md

**Comment by mmccool** [comment]
See updates in https://github.com/w3c/wot-architecture/pull/491 for Health Monitoring use case.

**Comment by mlagally** [comment]
smartcity-health*.md has been updated.
smartcity-geolocation.md still needs to be updated.
Filed a separate issue https://github.com/w3c/wot-architecture/issues/519
to simplify tracking.
Closing this issue.
