### ISSUE TITLE
Update Retail Use Case with Security and Privacy Considerations

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#494]
Fill in Security Considerations and Privacy Considerations sections (and remove redundant text elsewhere...)

**Comment by clerley** [comment]
Please assign retail to me.

**Comment by mmccool** [comment]
See also https://github.com/w3c/wot-security/issues/170 - S&P considerations for retail can be pulled in part from Conexxus S&P document.

**Comment by mlagally** [comment]
S&P considerations were added to the use case. Closing the issue.
