### ISSUE TITLE
Use Case for Education/Teaching

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#496]
Description: We are offering a practical course for the students where they can interact fully remotely with WoT devices and verify their physical actions via video streams. We have sensors and actuators like robots. Students then build mashup applications to deepen their knowledge of WoT technologies. Official page of the course is [here](https://campus.tum.de/tumonline/wbLv.wbShowLVDetail?pStpSpNr=950504601&pSpracheNr=1).

Question: Has there been any experimentation and experience with devices that can be used by multiple consumers at the same time? For reading properties and subscribing to events, it is quite straightforward but what about actions that take a "physical" time (like moving the robot, displaying a text etc.)? At the moment, we do not enroll many students and hope to not have any conflicts when two students want to move the robot at the same time. However, we would like to enroll more students and thus will have these conflicts soon enough. What would be the solutions for this and could they be described in a TD or explained in a standard way?

Possible implementation based solutions:
- **Assign each student a time slot.** First of all, putting such information in a TD is interesting since we would need to have a security scheme that can describe the time when a security scheme is valid. Should the TD change based on Consumer? Even if we can describe this, it is suboptimal since a student may not be doing any exercise at his/her allocated time but another student might be interested.

- **Queue the requests**. We can queue each request and execute them in their order of arrival. However, this induces a problem where a student would want to invoke an action (like moving a robot) and start reading a property influenced by this action (like the position of the robot) but another student's action invocation would change the first student's expectation. Furthermore, if one student invokes two actions in a row, their actual invocation order might change depending on the queue for each action

- **Require sequences for actions**. Instead of saying that an action can be executed at any time, the Thing listens for a message (the start of this action, a propertywrite or any other custom solution) and blocks the action invocations (or all interactions) of this Thing by other Consumers upon the arrival of this message for a certain duration. This is probably the most performant solution with regards to the experience of the user. However, the Thing needs to remember a state and to handle the request based on this state. Also, how would we describe this in a TD?

**Comment by mlagally** [comment]
Suggest to create a use case description in a template to describe the problem. This is related to  management of shared resources. (semaphores, transactinos, deadlock prevention, ...)

**Comment by mlagally** [comment]
The use case description was provided and merged to the repo.
Closing the issue.
