### ISSUE TITLE
Clear definition about Properties, Actions, and Events

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-architecture#51]
For the TD deliverable document we need a reference with definitions about WoT's Properties, Actions, and Events. There was the plan to place this in the architecture document. What is the status about this?

BTW: A good reference can be https://rawgit.com/w3c/wot-thing-description/master/proposals/simplified-td/index.html#interaction-model

**Comment by mlagally** [comment]
@sebastiankb Please take a look at the definitions in the terminology section. Are they sufficient?

**Comment by mkovatsc** [comment]
I updated the relevant sections starting from https://w3c.github.io/wot-architecture/#web-thing

**Comment by sebastiankb** [comment]
looks good

**Comment by mlagally** [comment]
Resolved in section 6.4
