### ISSUE TITLE
Which branch or tag corresponds to the release version

### ISSUE THREAD

**Issue by liuxing3169** [w3c/wot-architecture#529]
In other w3c repositories, the branch with'gh-pages' represents the latest released version, which branch in this repo corresponds to the latest released version?
https://www.w3.org/TR/2020/REC-wot-architecture-20200409/
thank you

**Comment by mlagally** [comment]
The REC version is on the master branch under https://github.com/w3c/wot-architecture/tree/master/publication/rec

**Comment by liuxing3169** [comment]
I got it, thank you very much @mlagally
