### ISSUE TITLE
Lifecycle section: Incorporate review feedback from security group

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#533]
See: https://github.com/w3c/wot-security/issues/169

**Comment by mlagally** [comment]
Arch call on 3.9.:
The Information lifecycle needds to be discussed with PING based on first draft text.
This should be ideally run by the security TF before.

**Comment by mmccool** [comment]
Issue https://github.com/w3c/wot-security/issues/169 has been closed as the review has been completed, but we expect further work to take place here to incorporate the suggestions into the Architecture document before this issue can be closed.  The above link to the closed wot-security issue is still relevant as it has the results of the review.

**Comment by mlagally** [comment]
Suggest to close and create a new issue when we receive new feedback from ping.
