### ISSUE TITLE
Lifecycle simplification

### ISSUE THREAD

**Issue by zolkis** [w3c/wot-architecture#561]
We should justify why do we have 3 lifecycles (system, device, data), and in addition we need to discuss application lifecycle.
Then, what is the relationship between them.
If there is value in factoring out 3 lifecycles, we should clearly express that value.
I would consider talking about lifecycle in general from use cases point of view, then talk about its system, device, data and application _aspects_.

**Comment by mlagally** [comment]
Arch call on 10.12:
Do you suggest to eliminate sections or to better explain what we heave been talking about?

**Comment by zolkis** [comment]
Listing use cases for all the 3 kinds of lifecycle would help making more clear what they were meant for.

**Comment by mlagally** [comment]
Arch call on 17.12.:
Use case(s) should be defined in the Use Cases TF
