### ISSUE TITLE
Review Binding specification chapter 9.5

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#599]
Split chapter to reflect recent decisions wrt. splitting of binding documents - describe different binding documents
New Modbus binding document, different ontology with dedicated vocabulary
Consider calling out different levels, e.g. protocols, media types, platforms need to be introduced

**Comment by egekorkan** [comment]
This chapter should be updated to reflect the changes in the binding restructuring

**Comment by mlagally** [comment]
MR has been merged. Closing the issue.
