### ISSUE TITLE
A Thing may be the abstraction of more than one entity.

### ISSUE THREAD

**Issue by maximelefrancois86** [w3c/wot-architecture#60]
The definition of a Thing is:

> An abstraction of a physical or virtual entity whose metadata and interfaces are described by a WoT Thing Description.

Shouldn't this definition be relaxed to account for more use cases:

> An abstraction of one or more physical or virtual entities whose metadata and interfaces are described by a WoT Thing Description.

For example, a Thing could be the abstraction of all the lights in a street.

**Comment by vcharpenay** [comment]
I think the fact a Thing can be the logical component of a device sort of includes these use cases. @mkovatsc, can you confirm?

Yet, it is maybe more accurate to define virtual/logical Things _only_ as the composition/aggregation of physical entities (and modify the definition as you suggest).

**Comment by mlagally** [comment]
Proposed term definition for terminology section: (19.2.)

An abstraction of a physical or a virtual entity whose metadata and interfaces are described by a WoT Thing Description. A virtual entity is the composition of one or more Things.
