### ISSUE TITLE
Relationship between "8.7 Protocol Bindings" and "9.5 WoT Binding Templates"

### ISSUE THREAD

**Issue by ashimura** [w3c/wot-architecture#608]
At some point, we started to use "Binding Template" as the name for one of the WoT building blocks for Protocol Bindings, and it seems to me that it would be better to add some more description about the relationship between the concept of "Protocol Bindings" and "Binding Templates" for developers to understand the concept and the concrete building block.

See also:
* [8.7 Protocol Bindings](https://w3c.github.io/wot-architecture/#sec-protocol-bindings)
* [9.5 WoT Binding Templates](https://w3c.github.io/wot-architecture/#sec-binding-templates)

**Comment by mlagally** [comment]
Since the binding document has undergone significant restructuring we have to check / align terminology and update the binding section in the architecture document.
Terminology needs to be aligned across all documents to prevent confusion among readers.

I suggest a joint editors call to identify and discuss needs for alignment.

**Comment by mlagally** [comment]
If we maintain separate protocol binding documents for different protocols, it would make sense to link these from the architecture specification to avoid a level of indirection.
A corresponding small section should be added to https://w3c.github.io/wot-architecture/#sec-binding-templates

**Comment by egekorkan** [comment]
These are maintained by the binding templates, I do not like duplicating content

**Comment by mlagally** [comment]
Arch call on 9.12.
Keep open

**Comment by egekorkan** [comment]
So I do not know why I was pinged (or assigned) but here is what the abstract of the new binding spec says:

> Binding Templates enable a Thing Description to be adapted to a specific protocol, data payload formats or platforms that combine both in specific ways. This is done through additional descriptive vocabularies, Thing Models and examples that aim to guide the implementors of Things and Consumers alike.

This means that the word "Binding Template" is the generic word and the Protocol Binding is one type of bindings and others are payload representation and platform. The introduction of the binding templates will be made better but it already has a bullet list and protocols is one of the points.

**Comment by benfrancis** [comment]
See also: https://github.com/w3c/wot-binding-templates/issues/143

**Comment by mlagally** [comment]
Arch call on June 23rd: 
Sebastian will create a MR with some introductory text to section "WoT Binding Templates"
