### ISSUE TITLE
Move terminology section from discovery to architecture spec

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#613]
Move the entire terminology section from discovery to architecture spec and align, if necessary.

Most of the terminology is required to understand the building block in chapter 9.
Consider if there are specific terms that should be kept separate.

**Comment by k-toumura** [comment]
At present, the following terms are listed in [the Discovery document](https://w3c.github.io/wot-discovery/#terminology):

| Terms in Discovery doc. | is already in Terminology section of Arch. doc? | is referred in Arch. doc? |
| --- | :-: | :-: |
| Anonymous TD | - | - |
| Discoverer | - | - |
| Discovery | ✓ | ✓  |
| Enriched TD | - |  - |
| Exploration | - | ✓ |
| Introduction | -  | ✓ |
| Thing Description Directory (TDD) | ✓ | ✓ |
| Partial TD | ✓ |  - |

So, should we do following?
- delete from Discovery: Discovery, Thing Description Directory(TDD), Partial TD
- move from Discovery to Architecture: Exploration, Introduction
- leave it intact in Discovery: Anonymous TD, Discoverer, Enriched TD
  - or, add their description to Architecture?

**Comment by mlagally** [comment]
@k-toumura 
Many thanks for looking into the details.
I think your first 2 bullets are the right thing to do.
On the 3rd bullet, I think the term "Anonymous TD" and "Discoverer" will be used in the Profile spec at some point in time, so I duggest to also move them.

**Comment by farshidtz** [comment]
I still believe that the term Discoverer is misleading; see https://github.com/w3c/wot-discovery/issues/216#issuecomment-923942848
Maybe it is worth reconsidering it as part of the migration.
