### ISSUE TITLE
Review Chapter 6.7 in relation to Binding Templates 4.1

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#617]
Currently, architecture talks about protocol bindings. This should be reviewed to sync with the 4.1 of the Binding Templates

**Comment by egekorkan** [comment]
In addition to my points in #625 , below are my review points:
- 8.7.2 mentions transfer protocol and not transport protocol

**Comment by mlagally** [comment]
Arch call on Dec 9th:
@egekorkan Do you plan additional work for that?

**Comment by egekorkan** [comment]
My review:

There are 3 types of requirements in chapter 8.7:
1. 8.7.1 Hypermedia-driven
2. 8.7.2 URIs
3. 8.7.3 Media Types

These are indeed correct and _somewhat_ reflected in the binding specification at chapter 4.1.1 Creating a Protocol Binding. I say somewhat because:

1. 8.7.1 Hypermedia-driven : This basically says that there has to be forms and how forms can be generated (by the Thing itself or by an external entity). This should be made more clear and ideally refer to TD spec and the assertion in the first sentence can be removed since it is also specified in the TD spec.
2. 8.7.2 URIs : Correct but there are discussions everywhere about making the IANA registration mandatory or not
3. 8.7.3 Media Types : I think this should be moved since media type and protocol are different things in my opinion. This corresponds to chapter 4.2 of the binding templates.

Even though this section is duplicate to binding templates, I would not oppose to its existence if the assertions are removed and some examples are given. Actually, this is a _perfect_ place to put some of the orphaned sections of the binding template such as B.1 (https://w3c.github.io/wot-binding-templates/#form-element)

**Comment by mlagally** [comment]
Arch call on June 23rd: no further work is expected. Closing the issue.
Please open individual tasks, if necessary.
