### ISSUE TITLE
Grammatical issue in the first para in the section "7.1 WoT Client"

### ISSUE THREAD

**Issue by srirama179** [w3c/wot-architecture#62]
**7.1 WoT Client**
> Figure 14 shows the basic scenario, where a Servient in client role, a WoT Client, is consuming an existing device that is augmented with a Thing Description (TD). The latter could be generated from digital descriptions already available for the device within the **_corresponding ~~the~~ IoT Platform_**. It could also be written by a developer using tools or even manually.

In the above highlighted text, the word "the" is unnecessary.

**Comment by mlagally** [comment]
Resolved in commit
https://github.com/w3c/wot-architecture/commit/3619abef5b3d29bea513096485c8605431f42df7
