### ISSUE TITLE
internationalisation requirements

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#620]
We need a new section to introduce i18n requirements.
This can be brief and reference the corresponding section of the TD spec.

**Comment by sebastiankb** [comment]
I'm not sure in which section it should be placed. Here would be a sample text for this section:


>Web of Things support interoperable internationalization and allows to use to work with multilingual data such as for User Interfaces. The design and implementation of multilingual Web of Things implementations is guided by the Thing Description [TD Reference] specification. It describes how human-readable text in different languages can be applied based on established standards such as from [[JSON-LD]] and [[BCP47]].

**Comment by mlagally** [comment]
Arch call on May 24th.
Add to the end of section "System integration"

**Comment by mlagally** [comment]
"System integration" seems not to be the right place,
rather create a new section under "System Concepts"
