### ISSUE TITLE
Move list of operations to the Thing Description specification

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-architecture#623]
The WoT Architecture currently provides a table of "well-known operation types for the Web of Things" in section [8.6.2 Forms](https://w3c.github.io/wot-architecture/#sec-hypermedia-forms).

We discussed on multiple calls that this table should be moved to the Thing Description specification, since that specification provides the canonical list of op types in section [5.3.4.2 Form](https://w3c.github.io/wot-thing-description/#form).

Currently every time a new operation type is added, the name has to be added to the Thing Description specification and then a description added to the architecture specification and the two have to be kept in sync.

**Comment by egekorkan** [comment]
Duplicate of https://github.com/w3c/wot-architecture/issues/606

**Comment by benfrancis** [comment]
Aha, thanks!
