### ISSUE TITLE
Explaining of WoT operations

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#626]
Currently, the architecture document does not explain in detail what the WoT operations really mean. If #606 is not merged, i.e. the table of op value stays here, there can be subsections explaining the meaning of these interaction with flows etc.

Also see https://github.com/w3c/wot-architecture/issues/606#issuecomment-957877898

**Comment by egekorkan** [comment]
Not sure what I should do here.

**Comment by mlagally** [comment]
Arch call on Dec 23:
This is related to the previous discussion on removing table 1.
@egekorkan and @mlagally will work together and consoldate the corresponding section.
