### ISSUE TITLE
Introduction does not mention section 6

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#628]
As seen in the screenshot below, the introduction does not mention section 6. Is this intentional?

![image](https://user-images.githubusercontent.com/20195407/139944853-b69105dd-a5f7-482b-a5c2-3c637a51e3a9.png)

Section 7 is also not mentioned but it is small anyways?

**Comment by mlagally** [comment]
Thanks @egekorkan for noticing. This is an oversight and will be fixed.
