### ISSUE TITLE
Why are Chapter 8 and 9 separated

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#630]
When I am updating another WoT specification and want to sync the updates with the architecture specification, it is confusing that there are two places any specification can look for: Section 8 and 9 for most, 9 and 10 for Scripting API.

- For Bindings it is 8.7 and 9.5
- For Scripting API it is 9.6 and almost entire 10
- For TD it is 9.1, 9.2 and bunch of subsections in 8

If we are to have information in the architecture specification that other specifications should sync with, it should be easier for other specifications to know where to update.

**Comment by mlagally** [comment]
Chapter 8 introduces the concepts in the abstract WoT system architecture.
The Building block chapter 9 contain overview / explainer level information on the corresponding building block documents.
I hope it is not too dificult for editors of other specifications to identify the relevant parts. 
Please make a contribution with a proposal if you think some specific change is needed.

**Comment by egekorkan** [comment]
I think that the minimum that needs to be done is renaming building blocks to specification documents. Other comments:

- System Architecture is almost an abstracted version of TD so I don't know the need for an extra TD chapter that needs to be synced separately. TMs are added only to the 9 whereas they are also part of the system architecture.
- 10.3 and 9.6 are definitely mergable in a way. @relu91 or @danielpeintner ?

I think that the amount of duplication of actual text and concepts should be reduced to make it easier to maintain, which is obviously failing given the high amount of misalignments.

**Comment by danielpeintner** [comment]
>  * 10.3 and 9.6 are definitely mergable in a way. @relu91 or @danielpeintner ?

Maybe the para in 10.3 can be added to the section 10.2 which talks about WoT runtime. Scripting for me is a runtime....

**Comment by relu91** [comment]
>10.3 and 9.6 are definitely mergable in a way. @relu91 or @danielpeintner ?

+1 for merging, 10.2 already correctly describes how a runtime relates to the Scripting API we don't need another paragraph
