### ISSUE TITLE
`arch-td-consumers-process` : Consumers MUST be able to parse and process the TD representation format, which is based on JSON [[!RFC8259]].

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#632]

**Comment by mlagally** [comment]
Other (binary) formats may exist, so I think the part after the comma should be removed.

**Comment by benfrancis** [comment]
This assertion could be worded better but overall I agree with it, see https://github.com/w3c/wot-architecture/issues/625#issuecomment-970549428

**Comment by sebastiankb** [comment]
I agree with @benfrancis this assertion is already covered by the TD spec in [Chapter 6 ](https://w3c.github.io/wot-thing-description/#sec-td-serialization), mainly with the assertion: 

>A TD Processor MUST be able to serialize Thing Descriptions into the JSON format [RFC8259] and/or deserialize Thing Descriptions from that format, according to the rules noted in § 6.1 Mapping to JSON Types and § 6.3 Information Model Serialization.

**Comment by mlagally** [comment]
arch call on 25.11.: remove
