### ISSUE TITLE
`arch-property-readable` : The state exposed by a Property MUST be retrievable (readable).

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#633]

**Comment by benfrancis** [comment]
I wouldn't mind if this was true, but it clearly isn't true because there's a `writeOnly` member of `PropertyAffordance`.

**Comment by sebastiankb** [comment]
There can be use cases that properties are defined only for writable purposes (eg, parameter settings) and other properties for readonly (e.g., read latest parameter settings). I think, it is not best practice and not really REST style. However, it does not hurt and at least would open the opportunity to retrofit existing implementations.

btw: I would be open to have a recommendation for the profile that says properties are always readable .

**Comment by mlagally** [comment]
arch call on 25.11.:
remove here, clarify in TD, consider mandating in profile

**Comment by sebastiankb** [comment]
PR clarifies the usage of readOnly and writeOnly in Properties in the TD spec https://github.com/w3c/wot-thing-description/pull/1306#pullrequestreview-820123507

Assertation in Arch can be removed
