### ISSUE TITLE
`arch-thing-bundling` : Things MAY be bundled together with a Consumer to enable Thing-to-Thing interaction.

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#634]

**Comment by benfrancis** [comment]
From https://github.com/w3c/wot-architecture/issues/625#issuecomment-970549428...

> * `arch-thing-bundling` : Things MAY be bundled together with a Consumer to enable Thing-to-Thing interaction.
> First time I am hearing this and I have no idea what it means. A consumer can form a mashup of things but this cannot magically create T2T interactions. At least no one has done in the WG/IG before as far as I know. Thankfully only a MAY assertion.

It is certainly possible for a single software application to act as both a WoT Consumer and a WoT Producer (actually WebThings Gateway does this), but I agree the idea of direct Thing to Thing interactions is purely theoretical and I've never really been convinced by that use case.

**Conclusion:** ❌ I think this could safely be removed.

---

**Suggested action:** Remove the assertion.

**Comment by mlagally** [comment]
Arch call on 25.11.: remove

**Comment by sebastiankb** [comment]
accidentally I  merged this directly to the main...

If there is a complain I will revert..

**Comment by mlagally** [comment]
@sebastiankb 
I'm not sure how you merged it - the MR is still open and apparently has merge conflicts.
Please revert the merge to ensure we can properly review in the call.

**Comment by mlagally** [comment]
Arch call on May 19th.
Text had been removed, closing the issue.
