### ISSUE TITLE
`arch-op-wellknown-compare` : Well-known operation types MUST be compared using a case-insensitive comparison.

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#637]
Please follow the process in https://github.com/w3c/wot-architecture/issues/641

**Comment by benfrancis** [comment]
From https://github.com/w3c/wot-architecture/issues/625#issuecomment-970549428...

> * `arch-op-wellknown-compare` : Well-known operation types MUST be compared using a case-insensitive comparison.

As far as I can see there's no mention of this in the Thing Description specification, which just lists the literal values in all lower case. It would be simpler if they had to be lower case

**Conclusion:** ❌ I don't have a strong opinion, but requiring lower case would be simpler.

---

**Suggested action**: Remove this assertion. Could also add an assertion to WoT Thing Description that operation names MUST be all lower case, but may not be backwards compatible.

**Comment by sebastiankb** [comment]
I think, this assertion talks about the op values: 

![image](https://user-images.githubusercontent.com/13832739/143048912-44bef93a-c0da-45f5-a488-44051a1e38cf.png)

The TD model defines this values as case-insensitive by the underlying TD ontology + JSON Schema definition. If there non case-insensitive values the validation should fail.  +1 to remove this assertion

**Comment by mlagally** [comment]
Arch call on 25.11. 
Ensure the TD spec mkes these op names case sensitive, 
the assertion can then be removed here.

**Comment by benfrancis** [comment]
https://github.com/w3c/wot-thing-description/issues/1303

**Comment by benfrancis** [comment]
> The TD model defines this values as case-insensitive by the underlying TD ontology + JSON Schema definition. If there non case-insensitive values the validation should fail. +1 to remove this assertion

Note that in the Architecture call @sebastiankb noted that this was a typo. As I understand it he said values are actually case sensitive and non-lower-case would be invalid.

**Comment by mlagally** [comment]
Arch call on 16.12:
There's an open issue in the TD dealing with it:
https://github.com/w3c/wot-thing-description/issues/1303
Architecture will wait for the TD to incorporate normative language before we close this issue.

**Comment by mlagally** [comment]
The TD issue in https://github.com/w3c/wot-thing-description/issues/1325 has been addressed, so Architecture can remove the corresponding assertion.
