### ISSUE TITLE
`arch-op-extension` : The set of predefined operation types MAY be augmented by Extension operation types chosen by applications.

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#638]
Please follow the process in https://github.com/w3c/wot-architecture/issues/641

**Comment by benfrancis** [comment]
From https://github.com/w3c/wot-architecture/issues/625#issuecomment-970549428...

> * `arch-op-extension` : The set of predefined operation types MAY be augmented by Extension operation types chosen by applications.
> See #619.

As you point out in #619, this directly contradicts the Thing Description specification.


**Conclusion:** ❌ This is a contradiction which should be removed.

---
**Suggestion:**: Remove the assertion.

**Comment by sebastiankb** [comment]
My impression is, this assertion comes from a time where it was kind of uncertain which operation types are possible in the future. TD 1.1 has now a kind of updated list based on the PlugFest experiences. Im not aware of others are required.
