### ISSUE TITLE
`arch-uri-scheme` : Eligible protocols for W3C WoT MUST have an associated URI scheme [[!RFC3986]] that is registered with IANA (see [[?IANA-URI-SCHEMES]]).

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#639]
Please follow the process in https://github.com/w3c/wot-architecture/issues/641

**Comment by benfrancis** [comment]
From https://github.com/w3c/wot-architecture/issues/625#issuecomment-970549428...


> * `arch-uri-scheme` : Eligible protocols for W3C WoT MUST have an associated URI scheme [[!RFC3986]] that is registered with IANA (see [[?IANA-URI-SCHEMES]]).

I strongly agree with this assertion, but let's continue the discussion in https://github.com/w3c/wot-binding-templates/issues/137.

**Conclusion:** ✔️ I strongly agree with this assertion.

---

**Suggested action:*** Move this assertion to WoT Thing Description.

**Comment by sebastiankb** [comment]
I agree with keeping and moving this assertion with some minor modification as discussed in https://github.com/w3c/wot-binding-templates/issues/137.

**Comment by mlagally** [comment]
I strongly agree with @benfrancis that this assertion should be kept, however it could be split into two parts. 
1. mandate URI scheme.
2. registration obligation - this could be recommeded but not required.

With these changes, the assertion can stay in the architecture specification.

**Comment by sebastiankb** [comment]
My proposal is to update the [Section 8.3](https://w3c.github.io/wot-thing-description/#protocol-bindings). Having this we can remove the assertion. I will provide a PR for it.

**Comment by sebastiankb** [comment]
PR is available, please review https://github.com/w3c/wot-thing-description/pull/1301

**Comment by mlagally** [comment]
Arch call on 25.11.: Remove from Arch, add to TD spec.

**Comment by mlagally** [comment]
The discussion about the content needs to happen in the TD group.

**Comment by sebastiankb** [comment]
I provided a PR for removing. The detail discussion about section 8.3 in TD spec should be continued in this issue  https://github.com/w3c/wot-thing-description/issues/1326
