### ISSUE TITLE
`arch-hypermedia-origin` : The hypermedia controls MUST originate from the authority managing the Thing that is providing the corresponding Interaction Affordance.

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#641]

**Comment by mlagally** [comment]
Decide on the way forward:
- clarify the assertion in the architecture specification
- move the text section to the TD specification
- delete from the architecture specification

Inform the editors of a corresponding WoT specification if you know that the same text should also be removed there.

Create a MR that handles the text/section that should be changed/removed/moved

If something is moved, another issue and MR for the TD spec needs to be done as part of this work.

**Comment by mlagally** [comment]
The owner of the issue should propose a way forward and take the review feedback in #615 by @benfrancis and @egekorkan into account.

**Comment by benfrancis** [comment]
From https://github.com/w3c/wot-architecture/issues/625#issuecomment-970549428...

> * `arch-hypermedia-origin` : The hypermedia controls MUST originate from the authority managing the Thing that is providing the corresponding Interaction Affordance.

I don't really understand what this means, but I'd guess it isn't really enforceable. Also, the previous assertion:

_"Protocol Bindings MUST be serialized as hypermedia controls to be self-descriptive on how to activate the Interaction Affordance."_

is arguably now contradicted by the WoT Profile specification, which defines details of a protocol binding which do not have to be self-described by a Thing.


**Conclusion:** ❌ This should probably be removed.

---

**Suggested action:** Remove the assertion.

**Comment by k-toumura** [comment]
The assertions related to hypermedia control, including this assertion, are too restrictive to define the entire WoT architecture.
I think it would be better to keep the section '8.6 Hypermedia control' to a general description without any assertions.

**Comment by sebastiankb** [comment]
I'm agree to remove as well.

**Comment by mlagally** [comment]
2 alternatives proposed:
Reword section or remove
@benfrancis @egekorkan @sebastiankb @k-toumura 
Please try to agree on a common way forward.

**Comment by egekorkan** [comment]
I still need to understand this assertion in order to reword it. @k-toumura could you provide an explanatory text about it?

**Comment by k-toumura** [comment]
I think this assertion is base on the idea that Thing creates its own TD and tells the consumer to what operation it can perform on the Thing itself.  In other words, it is assumed that the TD can be changed dynamically depending on the state of the Thing (like [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS)?).   So, I guess it is important that the source of the TD is authorized.

At this moment, there are not many Things that adopt such dynamic TD usage (@vcharpenay [implemented/proposed it on Plugfest two years ago](https://github.com/w3c/wot-thing-description/blob/main/proposals/hypermedia-control/README.md)), so I agree with removing this assertion.

**Comment by egekorkan** [comment]
In this case let's remove it :)
