### ISSUE TITLE
Remove op value table from Arch Spec

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-architecture#663]
The op value [table I ](https://w3c.github.io/wot-architecture/#table-operation-types) should be removed since this is already used by the [TD spec](https://w3c.github.io/wot-thing-description/#form).

**Comment by mlagally** [comment]
Arch call on 23.12:
REmove Table 1 form the architectuer spec
Change the sentence that references Table one to point to the Section in the TD that contains that table (5.3.4.2)
Simplify the text in the architecture document to just summarize the operations without specific details.
