### ISSUE TITLE
Review architecture document consistency

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#681]
Please review architecture document consistency by **Feb 4th.**

This includes:
- verifying terminology
- checking text in normative chapers
- verifying that assertions are fit for purpose
- proposing additional normative text, if required

For a reference of the document structure, please use https://github.com/w3c/wot-architecture/issues/646

If you find any problem that requires normative changes, please create an issue and a PR by **Feb 4th.** to allow 
for review and inclusion into the spec.

For all other problems, please create an issue in github.

**Comment by mlagally** [comment]
Arch call on May 11th: No further feedback expected, closing.

**Comment by egekorkan** [comment]
There are still assertions that need to be removed, so I would say that this check is not completed

**Comment by mlagally** [comment]
Remaining issues:
* [ ] https://github.com/w3c/wot-architecture/issues/635
* [ ] https://github.com/w3c/wot-architecture/issues/634
* [ ] https://github.com/w3c/wot-architecture/pull/737
* [ ] https://github.com/w3c/wot-architecture/issues/646

**Comment by mlagally** [comment]
Arch call on June 23rd:
All remaining issues have been addressed.
If there are individual smaller problems, please file a new issue and don't reopen these omnibus issues.
