### ISSUE TITLE
Introduction misses WoT Discovery

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-architecture#684]
Section [1. Introduction](https://w3c.github.io/wot-architecture/#introduction) does not even mention discovery.

Later in Section [8. WoT Building Blocks](https://w3c.github.io/wot-architecture/#sec-building-blocks) discovery is mentioned as "building block".

Hence, I assume discovery should be introduced in the introduction also.

**Comment by mmccool** [comment]
Yes, I noticed that too (I mentioned it in the Editor's call this morning) and was planning a PR to fix it.

**Comment by mlagally** [comment]
Arch call on June23rd:
McCool will create a MR by next week.
