### ISSUE TITLE
Merge "4. Device Categories" section into "3. Terminology" section (or delete)

### ISSUE THREAD

**Issue by k-toumura** [w3c/wot-architecture#705]
Since "4. Device Categories" section also describes about terminology, it might be better to merge it into "3. Terminology" section.

Or,  because none of the documents seem to use this classification terminology yet, we can simply delete the chapter.

**Comment by mlagally** [comment]
I think the section on device categories is very useful (and will be more useful) when we discuss profiles and deployment scenarios.
I prefer to keep it in the spec, I agree that we can move it under terminology.
