### ISSUE TITLE
Definitions for Entities that are Things

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#708]
Add two definitions:
- Device is a physical entity that has a network interface.  Devices can be described by a Thing Description and are a kind of Thing.
- Service is a software entity that has a network interface.  Services can be described by a Thing Description and are a kind of Thing.

The intention is that both Devices and Services, since they can be described by Thing Descriptions, are Things.

**Comment by mmccool** [comment]
Can also propose a definition for Virtual Thing: a kind of service that represents another Thing.  

Examples are Digital Twins and Shadow.   Shadows keep a copy of state of other Things.  Digital Twins may do that but may also have the ability to predict future states or behaviour, and may also maintain a history of past state (suggest a list of additional functionalities for Twins that if an entity has at least one can be called a Twin).

Will not include these in this PR, just putting out there for discussion.

**Comment by ashimura** [comment]
As I mentioned during the WoT Editors call yesterday on Feb. 15, it might make sense to look into the definitions and acronyms by oneM2M again:
* https://onem2m.org/using-onem2m/developers/basics
* https://onem2m.org/images/files/deliverables/TS-0011-Common_Terminology-V1_2_1.pdf

**Comment by k-toumura** [comment]
As a starting point for discussion, I've drawn a diagram of the Thing-related terms being discussed.
![terms](https://user-images.githubusercontent.com/30313213/154259573-b8bdc5ed-45ea-403c-b17f-09908694221f.svg)

In this diagram, I've separated the Physical Device from the software that makes them network-accessible (Physical Things).

(The diagram is attached as SVG file, so please feel free to fetch, rewrite, and upload it for discussion.)

**Comment by mmccool** [comment]
Thanks for the diagram.  Let's discuss next time we get a chance... but I'm thinking something even simpler, like a UML diagram showing subclass relationships among our definitions, would be helpful.

**Comment by mlagally** [comment]
This is a great diagram and unfortunately I just see it now after our architecture call. 
We should include it in the architecture specification, need to find a good plave.
