### ISSUE TITLE
Definitions for Virtual Thing, Shadow, and Digital Twins

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#709]
Proposed definition for Virtual Thing: A kind of Service that represents another Thing.

Examples are Digital Twins and Shadows.
* Shadows keep a copy of state of other Things. 
* Digital Twins may do that too (keep a copy of state of other Things) but may also have the ability to predict future states or behaviour, and may also maintain a history of past state (suggest a list of additional functionalities for Twins that if an entity has at least one can be called a Twin).

Note: the use of Virtual Thing for a "composite of other Things" should be deprecated and we should introduce a new term for that, perhaps "Composite Thing"

**Comment by mmccool** [comment]
Two additional thoughts:
- Proxies are another example of a Virtual Thing.  Proxies are Services that re-expose the same network interface as another Thing, but with modified access details (URLs, security schemes, etc).
- Regarding "Composite Things", I can imagine Composite Things that are ALSO Virtual Things.  I think a "Composite Thing" is an entity that has a Thing Description and describes the *relationship* between a set of Things.  If there is also a related Service that has a network interface that allows interactions with that set (for example, a Composite Thing might represent the set of all the lights in a room, and ALSO there might be a Service that allows all the lights to be turned on and off at once), the Composite Thing is also a Virtual Thing.  But I think the definition of the Composite Thing should be specifically about "An entity representing a set of relationships between Things", i.e. the *concept* of a collection, without implying there is a Service or Device with a network interface related to that collection (there may not be).

Propose we discuss whether these two definitions belong in this PR/issue or a new one.  For now I'll just do the ones in the description.

**Comment by mmccool** [comment]
@relu91 to avoid confusion with other interpretations of Virtual Thing, I am proposing the specific term "Service" to represent a Thing that is associated with a software entity instead of a physical device.  An example would be a TDD.  The fact is we already use "service" a lot for this.

A Virtual Thing is then a special case of a Service that "represents another Thing", examples being Shadows and Twins (and maybe Proxies).

We have also used "Virtual Thing" to represent a *conceptual* collection that may not have a network interface, or a representation of another entity like a location.  I think these are valid cases of "Things" but would like to exclude the use of "Virtual Thing" for these unless there is an associated Service.  We can invent new names for these kinds of Thing (e.g. Composite Thing, Location Thing) as needed.

Also, everything with "Thing" in the name is a Thing.  I think a Venn diagram would be useful...

**Comment by mmccool** [comment]
Also, not all Services are Virtual Things.  A Directory does not "represent" something else, it provides its own function.  Other kinds of non-representational Services might include analytics engines, time series databases, key-value stores, etc.

**Comment by mmccool** [comment]
Regarding if we change the term we should explain the change: right.  Let me at least make sure the change log explains it...

**Comment by mmccool** [comment]
Also, I think we have already moved away from "Things are physical devices", e.g. we talk in Discovery about a Directory being a Thing, that is how the ontology is set up, etc.  I think Services and Virtual Things are subclasses of Thing.  I guess we could *also* define "Physical Things" as Things associated with a specific physical device.

**Comment by relu91** [comment]
> Also, I think we have already moved away from "Things are physical devices", e.g. we talk in Discovery about a Directory being a Thing, that is how the ontology is set up, etc.

Totally fine with that! I actually encouraged this transition. 

Probably what got me off-guard was the "represent another Thing" part. However, I would be fine with:
 > In my PR I plan to define Services and Virtual Things as subclasses of Thing, and Virtual Things as a subclass of Services
 
However, I'm afraid that the ideal solution (to properly describe a complex setup)  is to discuss this point:
>  guess we could also define "Physical Things" as Things directly associated with (allowing direct access to the affordances of) a specific physical device. That would be a logical counterpart to "Virtual Thing"; then we would have "Virtual Thing is to a Service as a Physical Thing is to a Device".

>  Location (a Thing without a network interface) is a Physical Thing (my definition of Device is that it has a network interface)

Well, I think there's no ambiguity here if we follow the definitions: a Location is a Virtual Thing. But I got your point that outsiders might find that surprising.

**Comment by k-toumura** [comment]
> I think a Venn diagram would be useful...

I posted a diagram of Thing-related terminology in https://github.com/w3c/wot-architecture/issues/708#issuecomment-1041415429 .
Please feel free to use this diagram to discussion.

**Comment by mmccool** [comment]
OK, I created PR #711 that includes definitions for these terms and the ones in Issue #708.  Review away.
