### ISSUE TITLE
Outdated note on partial TD ?

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#714]
Please check if the note in the terminology / partial TD definition is still accurate.
From a cursory read of the scripting spec, the produce method requires a fully validated TD.

**Comment by danielpeintner** [comment]
@egekorkan not sure now...
Do you expect any change in the Scripting API document?

**Comment by egekorkan** [comment]
> Do you expect any change in the Scripting API document?

No I don´t think so, both documents seem fine regarding this definition?

**Comment by mlagally** [comment]
The link in the informative note is wrong.
It points to a published version, which does not mention partial TDs.

**Comment by mlagally** [comment]
Arch call on 10.3.:
Agreed to remove the link.
