### ISSUE TITLE
Mention Security also as a building block

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-architecture#72]
In the abstract only TD, Binding, and API is mentioned as building blocks. Security should be also mentioned here as a building block.

**Comment by mlagally** [comment]
@sebastiankb In my understanding the building blocks refer to specifications / system components. Security is a cross-cutting issue which is reflected in a guidelines document.
I suggest, we don't add it as a separate building block.

**Comment by mkovatsc** [comment]
"So WoT does not provide security?"

**Comment by mlagally** [comment]
@mkovatsc There is a security chapter in the document. However in my understanding WoT allows to use existing security mechanisms but does not define a new "system component" for security.
The TD only offers a description mechanism.

**Comment by mlagally** [comment]
@mkovatsc There is a placeholder for this text in section 7.4.
Text still needs to be written. See https://github.com/w3c/wot-architecture/issues/78

**Comment by mkovatsc** [comment]
Yes, I put it the placeholder there.

@mmccool We would need a short document summary from the security task force.

**Comment by mkovatsc** [comment]
Since we agreed that it should be there, we should close this issue -- we have https://github.com/w3c/wot-architecture/issues/78 assigned to @mmccool to implement.
