### ISSUE TITLE
Define and discuss hubs

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#724]
This is a carry forward for the open tasks from https://github.com/w3c/wot-architecture/pull/603 to be able to merge that PR.

- [ ] update Edge Device section to discuss hubs vs. gateways
- [ ] add explicit definitions for hubs and gateways to terminology
- [ ] make sure use of "Gateway" in "Smart Home Gateway" is consistent with definition of "Gateway" (e.g. if it manages local devices, and is NOT just a proxy... maybe it should be a "Smart Home Hub"?
- [ ] Explicitly allow for star as well as p2p topologies in architectural patterns (addressing https://github.com/w3c/wot-architecture/issues/585)
- [ ] cite use of hubs as a place to locate "digital twins", and along the way clarify the various functions that a digital twin might perform, and which are optional (e.g. protocol conversion, state caching, simulation, prediction, etc).  A "simple" digital twin might just do protocol conversion and state caching, for instance, and these simple twins are commonly supported by hubs.

**Comment by chachamimm** [comment]
"Gateways" is a feature that enables communication between two or more different communication protocols, For example, IP protocol and non IP protocol.
"Hubs" is α feature that concentrates lines used to physically connect communication devices such as IoT devices, PC and so on.

"Gateways" is a feature of Network Layer. "Hubs" is a feature of Datalink Layer.

Equipments of "Gateways" have "Gateways" feature and "Hubs" feature. Physical lines should be concentrated.  If equipments of "Gateways" have  "Hubs" feature, it would be convenient. 

I think we should discuss equipments and features separately.

**Comment by egekorkan** [comment]
I agree with the definitions proposed by @chachamimm . From my experience, gateways and hubs are not as commonly defined as switches, routers and access points. Is there any reputable, non-biased source that we can ideally cite in our specs? If I google for both of them, I only find products of companies or somewhat biased sources

**Comment by mlagally** [comment]
Arch call on June 23rd: decide to close.
