### ISSUE TITLE
Implementation report - remaining tasks

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#725]
This is a carry forward of remaining tasks from https://github.com/w3c/wot-architecture/pull/707
- [x] update HTML template to remove old content
- [x] update title and boilerplate in template to be relevant to current round
- [x] add testimonials
- [x] add descriptions of implementations
- [x] update extract scripts to render assertions using file input, put output in assertions.csv
- [x] update output of report generation tool to put its assertions in template.csv
- [x] run assertion tooling 
- [ ] #758
- [ ] #759
- [x] #755
- [x] update editors
- [x] update links to repos
- [x] update copyright dates
- [x] #756
- [x] #757
- [x] update README 
- [x] update templates
- [x] remove old information e.g. leftover from last TD report

**Comment by mmccool** [comment]
updated list of todo, including things I've already done just to keep track (and not repeat tasks)

**Comment by mmccool** [comment]
A few more updates here: https://github.com/w3c/wot-architecture/pull/732

**Comment by mlagally** [comment]
I converted 3 tasks to separate issues to make the task better manageable.
