### ISSUE TITLE
Outdated README in testing subdirectory

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#729]
The readme in the testing directory referes the ThingDescription and needs to be updated for Architecture:

https://github.com/w3c/wot-architecture/blob/main/testing/README.md

**Comment by mmccool** [comment]
Updating the README is already mentioned as a subtask in https://github.com/w3c/wot-architecture/issues/725.
There is also now a PR available (cited from the above issue) that updates the README and cleans out some other things, and also updates the report.

Going to close this issue and use the one above to track progress on the report.
