### ISSUE TITLE
Duplicate Assertions on Protocol Bindings

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#735]
While working on https://github.com/w3c/wot-architecture/issues/676, I have realized that there are the following assertions and they mean the same thing:
- At 6.6.2
> Form fields are optional and MAY further specify the expected request message for the given operation. 
- At 6.7.3
> Protocol Bindings MAY have additional information that specifies representation formats in more detail than the media type alone. 
These are not exactly the same thing but the first one is a superset of the latter.

**Comment by egekorkan** [comment]
Also, the last part of the following sentence says the same thing but without an RFC assertion:
> A form can be viewed as a statement of "To perform an operation type operation on form context , issue a request method request to submission target " where the optional form fields may further describe the required request.

**Comment by mlagally** [comment]
@ege, can you please create a PR to resolve the issue?

**Comment by mlagally** [comment]
> Also, the last part of the following sentence says the same thing but without an RFC assertion:
> 
> > A form can be viewed as a statement of "To perform an operation type operation on form context , issue a request method request to submission target " where the optional form fields may further describe the required request.

This is just explanatory text, I don't think we have to make it a normative assertion.

**Comment by mlagally** [comment]
Arch call on June23rd: decide to close.

**Comment by egekorkan** [comment]
I don't know why this issue is closed but it is not done
