### ISSUE TITLE
What does form context mean?

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#736]
The section 6.6.2 at https://w3c.github.io/wot-architecture/#sec-hypermedia-forms mentions the word `form context`. However, I do not exactly understand what it means. It is not `href`, not `op`, not `contentType` or extra protocol vocabularies. I am guessing it means the actual form but still not very sure.

**Comment by mlagally** [comment]
It is defined in the  CoRAL spec, which is referenced in that paragraph.
> W3C WoT defines forms as new [hypermedia control](https://w3c.github.io/wot-architecture/#dfn-hypermedia-control). Note that the definition in [CoRAL](https://w3c.github.io/wot-architecture/#bib-coral) is virtually identical, and hence compatible. A form is comprised of:

> a form context,
an operation type,
a submission target,
a request method, and
optionally form fields.
