### ISSUE TITLE
Clean up new TLS S&P Considerations

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#753]
Recently merged [PR #747](https://github.com/w3c/wot-architecture/pull/747) regarding use of TLS, but...

- reference for TLS would be good
- mention version of TLS?  Of just "up-to-date version"
- mention DTLS as suitable in case of UDP-based protocols
- Two uses of "generally" in the same sentence - needs english cleanup

Please comment below if you see anything else that needs fixing.

**Comment by mlagally** [comment]
@mmccool 
> * reference for TLS would be good
TLS 1.3: https://datatracker.ietf.org/doc/html/rfc8446

> * mention version of TLS?  Of just "up-to-date version"
Including a statement that the use of "compromised or legacy" algorithms are discouraged, unless a device cannot be upgraded to a better algorithm.
 Do you also want to mention 1.2? 

> * mention DTLS as suitable in case of UDP-based protocols
definitely.

> * Two uses of "generally" in the same sentence - needs english cleanup

**Comment by mlagally** [comment]
Arch call on June 23rd:
McCool will try to fix before next week.
