### ISSUE TITLE
`arch-schema`: Thus, the corresponding Interaction Affordances SHOULD declare a data schema to provide more detailed syntactic metadata for the data exchanged.

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#766]
Not sure if this is still relevant. TD does not constrain the TD documents in such a way so it is weird that arch spec asks for more constraints on the TD, compared to the TD spec itself.

It is a SHOULD assertion but still weird I think. 

Coming from #646

**Comment by mlagally** [comment]
Arch call on June 23rd: architecture gives a high level overview and this level of general requirement is appropriate here. Further details should be described in other specs as child assertions.
Conclusion is to keep the assertion.

**Comment by egekorkan** [comment]
But this is not a high level overview. It's a specific assertion on the td documents that the td spec doesn't impose. What's the reason for keeping it?

**Comment by mlagally** [comment]
Architecture call on 30.6.:
It is a reasonable assertion for architecture: 
Textual improvement:
Thus, the Interaction Affordance for structured data types SHOULD be associated with a [data schema](https://w3c.github.io/wot-architecture/#dfn-data-schema) to provide more detailed syntactic metadata for the data exchanged.
Details should be specified in the TD specification.

**Comment by mlagally** [comment]
This change was applied to the spec, closing the issue.
