### ISSUE TITLE
Remove or rephrase sentence around Trusted Networks

### ISSUE THREAD

**Issue by ComputerBear** [w3c/wot-architecture#770]
This issue is part of the PING privacy review https://github.com/w3cping/privacy-request/issues/86

In section 5.4 of this spec covering remote access there is this sentence "When the controller is in the home network it is a trusted device and no additional security or access control is required." Given all of the advice given about this in security sections 12.4 and 12.5, it seems odd to have this conflicting statement earlier in the spec.

I would advise either removing the sentence, or rewording to say that additional security/access control is only recommended in trusted networks.

**Comment by mmccool** [comment]
This is true, that was an oversight... the discussion down under Privacy Considerations was supposed to have replaced it.  I'll make a PR to repair this.

**Comment by mlagally** [comment]
@mmccool Can this be closed?
