### ISSUE TITLE
Highlight normative sections via links in introduction

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-architecture#772]
Follow-up of #629, we should put some links in the introduction about the normative sections that come later in the document

**Comment by mlagally** [comment]
There's already a corresponding section in the introduction:

> This specification serves as an umbrella for W3C WoT specifications and defines the basics such as terminology and the underlying abstract architecture of the W3C Web of Things. In summary, the purpose of this specification is to provide:

> a set of application domains in [4. Application Domains](https://github.com/w3c/wot-architecture/issues/772#sec-application-domains) that were considered to identify use cases for the W3C WoT Architecture,
> a set of common deployment patterns in [5. Common Deployment Patterns](https://github.com/w3c/wot-architecture/issues/772#sec-common-deployment-patterns),
> a definition of the abstract architecture in [6. Abstract WoT System Architecture](https://github.com/w3c/wot-architecture/issues/772#sec-wot-architecture),
> an overview of a set of WoT building blocks and their interplay in [7. WoT Building Blocks](https://github.com/w3c/wot-architecture/issues/772#sec-building-blocks),
> an informative guideline on how to map the abstract architecture to possible concrete implementations in [8. Abstract Servient Architecture](https://github.com/w3c/wot-architecture/issues/772#sec-servient-implementation),
> informative examples of possible deployment scenarios in [9. Example WoT Deployments](https://github.com/w3c/wot-architecture/issues/772#sec-deployment-scenario),
> and a discussion, at a high level, of security and privacy considerations to be aware of when implementing a system based on the W3C WoT architecture in [10. Security Considerations](https://github.com/w3c/wot-architecture/issues/772#sec-security-considerations) and [11. Privacy Considerations](https://github.com/w3c/wot-architecture/issues/772#sec-privacy-considerations), respectively.

**Comment by mlagally** [comment]
@egekorkan 
Not sure what you are missing, can we close this issue?

**Comment by egekorkan** [comment]
So the main reason behind this issue is the fact that the arch spec has quite a bit of normative text that gets lost behind the informative introduction which goes way further than what an introduction should be. This results in readers (including the WG) not taking the specification seriously which actually has assertions that affect all the other WoT specifications. This was the minimum effort needed to fix this problem

**Comment by mlagally** [comment]
@egekorkan 
Please review https://github.com/w3c/wot-architecture/pull/794 and let me know of any further suggestions for improvements.
