### ISSUE TITLE
String matching of Web links

### ISSUE THREAD

**Issue by xfq** [w3c/wot-architecture#775]
Links
https://w3c.github.io/wot-architecture/#sec-hypermedia-links

> Link relation types are either a set of predefined tokens that are registered with IANA, (e.g. <code>stylesheet</code>), or extension types in the form of URIs. Extension relation types *MUST* be compared as strings using a case-insensitive comparison. (If they are serialized in a different format they are to be converted to URIs). Nevertheless, all-lowercase URIs *SHOULD* be used for extension relation types.

I assume it uses ASCII case-insensitive matching instead of Unicode full casefold matching?

If so, it might be useful to link to https://infra.spec.whatwg.org/#ascii-case-insensitive to make it clear.

**Comment by mlagally** [comment]
Resolved via #795
