### ISSUE TITLE
Architecture (TAG) Review

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#797]
Work with TAG to get a review by the architecture architecture group.
https://tag.w3.org/workmode/

See also #621

**Comment by mlagally** [comment]
Work with TAG to get a review by the architecture architecture group.

**Comment by rhiaro** [comment]
Hi @mlagally. TAG review was requested a few months ago, and we filed [our review](https://github.com/immersive-web/raw-camera-access/pull/12/commits/ef171a587c883d37f3a3bf272551105a7c4e40a5) on the request issue. It's quite long though. Would you prefer if I split it up into multiple issues on this repo instead, or is it okay for you to work with?

**Comment by mlagally** [comment]
Hi @rhiaro,
many thanks for your extensive review and constructive feedback.
We will review the entire feedback carefully in today's architecture call, however it would be very useful for us, if you could create several issues, so we can adress them individually and have focused follow-up conversations in these issues.

**Comment by rhiaro** [comment]
Sorry for the delay, and I note that you had already split out a few of my points of feedback. I've now created issues for the rest, I hope that helps. Thanks again for your work on this.

**Comment by mlagally** [comment]
@rhiaro Thanks for all your review feedback. We have addressed many of them and provided feedback in the individual issues. Others are in work and will take a bit more time, since they depend on implementation reports that are yet to come. I'm closing this issue to avoid fragmented discussions.
