### ISSUE TITLE
Reconsider 2 normative assertions, move to TD spec?

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#810]
<span class="rfc2119-assertion" id="arch-binding-templates-media-type-parameters">
            The media type [[!RFC2046]] identifies these formats, while media type parameters MAY specify them further.</span>
            <span class="rfc2119-assertion" id="arch-binding-templates-media-type-optional-parameters">
            Forms MAY contain the media type and optional parameters in additional form fields such as a content type 
Member
</span>

**Comment by rhiaro** [comment]
(Cross linking to TAG feedback https://github.com/w3ctag/design-reviews/issues/736)

**Comment by mlagally** [comment]
Resolved by #790
