### ISSUE TITLE
Review for redundant normative statements [TAG feedback]

### ISSUE THREAD

**Issue by rhiaro** [w3c/wot-architecture#816]
Some normative statements are redundant - eg. in [12.1.1 Thing Description Private Security Data Risk](https://w3c.github.io/wot-architecture/#sec-security-consideration-td-private), "MUST ensure that only Public Security Metadata is ever stored" and "MUST ensure that no Private Security Data is included" seem to be saying the same thing from different directions.

Suggest reviewing all normative statements for this, and rephrasing where possible.

(From https://github.com/w3ctag/design-reviews/issues/736)

**Comment by mlagally** [comment]
We will review all assertions and identify those that are redundant as part of the implementation report work. 
These assertions will be converted to regular text.

**Comment by mlagally** [comment]
Arch call on Oct. 13:
Review has been done. 
2 follow up issues were created:
#852, #851
