### ISSUE TITLE
Review for unnecessary normative statements [TAG feedback]

### ISSUE THREAD

**Issue by rhiaro** [w3c/wot-architecture#817]
Some normative statements appear to provide context/background/similar rather than strictly describe normative requirements - eg. in [8.1.2 Links](https://w3c.github.io/wot-architecture/#links), that "Things MUST be hosted on networked system components [..]". Apologies if this has been misunderstood, but this seems more of a foundational premise than a feature to test for conformance purposes.

Suggest reviewing for such statements and rephrasing/moving/removing as appropriate.

(From https://github.com/w3ctag/design-reviews/issues/736)

**Comment by mlagally** [comment]
Arch call on Sept 8th:
Several normative statements have been weakened from "MUST" to "SHOULD", specifically in the security section. Some redundant assertions have been removed in security.

Group-wide review will be performed when the contributions from implementors for the implementation report will be available.
We are collecting testing input and will check, which assertions need to be clarified and which are at risk.

**Comment by mlagally** [comment]
Arch call on Oct 13th:
Nextstep:
Review at risk assertions in the implementation report:
https://w3c.github.io/wot-architecture/testing/report11.html
