### ISSUE TITLE
Provide implementation report on architecture for node-wot

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#829]
We need to understand features and sections that are at risk.

Please provide the manual.csv before Sept 21st.

**Comment by danielpeintner** [comment]
I provided a first WIP PR, see https://github.com/w3c/wot-architecture/pull/839.

Question: Where are the manual.csv meant to be placed in the repo?

**Comment by mlagally** [comment]
@danielpeintner 
Please put your input under: https://github.com/w3c/wot-testing/tree/main/data/input_2022/Architecture/Results
and create a MR there.

**Comment by danielpeintner** [comment]
FYI: I created https://github.com/w3c/wot-testing/pull/405

**Comment by mmccool** [comment]
Done, but needs more work (only one assertion marked as pass).  See IR update PR: https://github.com/w3c/wot-architecture/pull/848

**Comment by mmccool** [comment]
done (updated results included in IR).
