### ISSUE TITLE
Refine Terminology for WoT Runtime

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#83]
A WoT runtime can include several sub-components to handle communications, scripting, and protocol bindings.  Several aspects of the specification, for example scripting, relate to only one of these components.   This has an impact on how and where we discuss security considerations, among other issues.

Therefore the architecture document should define these sub-components and given them specific names.

**Comment by mlagally** [comment]
@mmccool Which components do you have in mind? Do they have to exist on each devices that carry a WoT runtime?

**Comment by mkovatsc** [comment]
@mmccool It sounds more like you describe the whole Servient. The WoT Runtime should be the component that instantiates Consumed Things and Exposed Things as software objects, manages their state, and generates the TDs. It communicates with other components such as the Binding implementations and application scripts (the WoT Scripting API being one way).

We decided to update [Figure 17](https://w3c.github.io/wot-architecture/images/architecture-implementation.png)  under [Servient Implementation](https://w3c.github.io/wot-architecture/#servient-implementation) with [Figure 18](https://w3c.github.io/wot-architecture/images/arch-simple-conf-wot-servient.png), which needs some more polishing.

**Comment by mkovatsc** [comment]
Also see https://github.com/w3c/wot-architecture/issues/35#issuecomment-467022651

**Comment by mlagally** [comment]
Arch call on 7.3.:

Add the following definition to the terminology section:

The WoT Runtime should be the component that instantiates Consumed Things and Exposed Things as software objects, manages their state, and generates the TDs. It communicates with other components such as the Binding implementations and application scripts (the WoT Scripting API being one way).

**Comment by mlagally** [comment]
Closing the issue to only have one discussion thread.
Continue the discussion in : https://github.com/w3c/wot-architecture/issues/130
