### ISSUE TITLE
Thing Description in High-level architecture

### ISSUE THREAD

**Issue by k-toumura** [w3c/wot-architecture#86]
In [Figure 14](https://w3c.github.io/wot-architecture/#high-level-application-device), Thing Descriptions are placed in each Servient.  But it is not clear that TD in the Application Servient describes for.
So I've updated these figures as below.  The intension of this update is to clarify which Servient is described by the TD and which Servient use the TD to interact others.  And these pictures are consistent with [Figure 16](https://w3c.github.io/wot-architecture/#architecture-concept), I think.

![Alternative of Figure 14](https://user-images.githubusercontent.com/30313213/53294933-c7ea0100-3833-11e9-9ca9-39515e6a9676.png)
![Alternative of Figure 15](https://user-images.githubusercontent.com/30313213/53294940-db956780-3833-11e9-87ea-3f30d2998f67.png)

What do you think of these figures?

Original PowerPoint file is [here](https://github.com/w3c/wot-architecture/files/2897564/arch-high-level-alt.pptx).

Edit(Feb 24): Removed a term 'Servient', because it is not yet defined at this section and not suitable for high-level architecture description.

**Comment by mkovatsc** [comment]
Very good, I also noticed this issue, but forgot to document. Thanks!

**Comment by mlagally** [comment]
@Thanks very much @k-toumura for thorough reading and drafting the pictures.
I noticed that you are using a different graphics style from the one we had earlier.
We should discuss the graphics style in the call this week and see how we can align it.

**Comment by mlagally** [comment]
For the time being I'm adding this diagram additionally to the document to facilitate the discussion.

**Comment by mlagally** [comment]
PR: https://github.com/w3c/wot-architecture/pull/87
