### ISSUE TITLE
Siemens-Logilab implementation description

### ISSUE THREAD

**Issue by wiresio** [w3c/wot-architecture#867]
Was already submitted in https://github.com/w3c/wot-testing/pull/384 and got lost. Respective file is [here](https://github.com/w3c/wot-testing/pull/384/files#diff-4de94d34abca8ca197e626081bfc12b6dd519618653dc0bb4e810f0f75ca19a4).

**Comment by mlagally** [comment]
This was done. Approved to close in arch call on Nov 30
