### ISSUE TITLE
Use Case due diligence

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-architecture#869]
An initial assessment was done earlier this year.

The task is to complete the assessment for architecture at:

https://github.com/w3c/wot-usecases/blob/main/USE-CASES/coverage.csv

See also: https://github.com/w3c/wot-usecases/blob/main/USE-CASES/coverage.md

**Comment by sebastiankb** [comment]
Coverage does not include the full results from TD. There is a PR for it https://github.com/w3c/wot-usecases/pull/197

In my view, this task can be done "by PR transition". Today we should concentrate on the [PRs as discussed in mailing list](https://github.com/w3c/wot-architecture/pulls?q=is%3Apr+is%3Aopen+label%3A%22by+CR+transition%22).

**Comment by mlagally** [comment]
Arch call on April 20.:
 This has been done at the high level in the coverage.csv in the use cases TF.
