### ISSUE TITLE
Replace the figure of the Building Blocks

### ISSUE THREAD

**Issue by mryuichi** [w3c/wot-architecture#88]
This issue is a proposal to replace the figure of the Building Blocks to a new one. Because some components of the current Building Blocks have been not well defined yet.  The below is my proposal. 

![images](https://github.com/mryuichi/documents/blob/master/images/arch-new-building-blocks.png?raw=true)

As already discussed, consideration of the use cases and the requirements derived therefrom resulted in noting that there are three types of entities. The figure shows the functional architecture that commonly applies to those three entity types.
The “WoT Runtime” functionally realizes operations based on interaction model described in Thing Descriptions, and is the central functionality of a WoT Servient. Based on a Thing Description, the WoT Runtime instantiates ExposedThing and ConsumedThings in a WoT Servient, and they provide functions used by applications, proxies and devices to serve as server’s and/or client’s roles. For example, when a WoT Servient is a device, an ExposedThing gets instantiated based on the device’s Thing Description. Regarding those operations to manage the lifecycle of an ExposedThing such as retrieving and/or serving Thing Descriptions, instantiating an ExposedThing based on the Thing Descriptions and terminating an ExposedThing, the details of the operation vary among different kind of devices. The WoT Servient Life Cycle Management (LCM) encapsulates those lifecycle operations. It uses internal interfaces to realize the lifecycle management of ExposedThings. The LCM is an application that runs on top of the WoT Runtime. The WoT Scripting API is one implementation of such an internal interface that includes functionality to realize the lifecycle management of ExposedThings. When a WoT Servient is an application or a proxy, the lifecycle management of ConsumedThings are realized in the same manner as that of ExposedThings. The WoT Runtime provides an interface to operate on the interaction model. This interface is defined as an abstract interface (the “Abstract Interface” in the figure [TDB?]). For this abstract interface to be used to interact with other WoT Servients or Web Server/Clients in practice, concrete bindings to underlying protocols need to be selected and used. It is the REST protocol that is most commonly used as the WoT interface on the Web. Other protocols such as CoAP, MQTT and WebSocket are also commonly used, and the protocol bindings enable the use of those protocols to interact with other Web Servients and Web Servers/Clients. Note that Web Servers and Clients are “Web Objects” that can directly interact with WoT Servients through the WoT interface even though they are not designed on the WoT interaction model. The overwhelming majority of existing sensors and devices are not implemented as Web Objects. The Device interface adapter represents the functionality to translate the native interface of those diverse kind of devices to/from the Abstract interface. As for the interfaces to existing devices, there are standards in each domain such as Home, Building and Factory. Moreover, the standards adopted by nations and even regions are often different, adding more complexity. Although in the future a framework for native protocol translation may be considered that eases the development of such translation work, it is not in the scope of the current WoT charter, therefore, the translation functionality is just called “Device interface adapter”.

**Comment by mlagally** [comment]
@mryuichi many thanks for your work.
Can you please create a PR with this proposal that shows how the existing text is replaced by the new proposal? This will allow easier handling of the proposal in tomorrow's call.

**Comment by mryuichi** [comment]
OK. I have done.
The description of the building blocks is inserted in the beginning of section 6.

**Comment by mkovatsc** [comment]
In other pictures the application sits outside the runtime, controlling the latter through an API such as the WoT Scripting API. I would recommend to remove the "(application)" and put it as "Application" in a box on top of the runtime system.

Either "WoT Runtime" or correct "Runtime System" -- just "runtime" is not a proper term. I would recommend "Runtime System" to avoid the unnecessary special definition of WoT Runtime (see #35 )

I am a but confused about the emphasis on the "WoT Servient Life Cycle Management". Every runtime system needs a form of life cycle management for what it instantiates (in our case the Thing software objects). Furthermore, it is not the Servient Life Cycle. The Servient contains the runtime system.

Device interface adapter is too specific. Originally we had "System API" to also enable local hardware or abstract services such as a database (through a Database Thing with corresponding affordances).

**Comment by mlagally** [comment]
Will revisit this issue once we have a consolidated spec that integrates the changes discussed on 14.3.

**Comment by mmccool** [comment]
So, I've been working on a new set of figures to resolve issues around whether or not the scripting API is a mandatory part of the WoT Runtime or not.   However, my new figures don't include the ExposedThing or ConsumedThing objects, and probably they should to align with the one above and the text...

**Comment by mlagally** [comment]
@mmccool I'm not clear about your comment. Do you want to update your figure to reflect the text or does the text have to be aligned?

**Comment by mlagally** [comment]
call on 21.3.
Consider https://github.com/w3c/wot-architecture/blob/master/images/wot-building-blocks-abstract.png to satisfy this issue.
