### ISSUE TITLE
TLS/DTLS Version Assertions Ambiguous

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-architecture#885]
The following assertions are a bit ambiguous: arch-security-consideration-tls-1-3, arch-security-consideration-tls-1-2, arch-security-consideration-dtls-1-3, arch-security-consideration-dtls-1-2
- In particular, the (d)tls-1-3 assertions are currently SHOULD for versions 1.3, then others are MAY for 1.2
- This is more confusing than necessary since what we really wanted was to say use 1.2 at least
- Also, the DTLS-1.3 assertion is at risk due to lack of libraries for it (it is a recent spec release).  But if this assertion does not make it into the spec, the related MAY assertion for DTLS-1.2 alone makes it sound like it is not that strongly recommended, which was not the intention.

The Security TF talked about this and would like to make the following changes to both 1-2 assertions, which are editorial in nature and do not change the intent or implementation requirements (and we already have test cases):

Current text: 
- If TLS 1.3 cannot be used for compatibility reasons but secure transport over TCP is appropriate, TLS 1.2 [RFC5246] MAY be used.
- If DTLS 1.3 cannot be used for compatibility reasons but secure transport over UDP is appropriate, then DTLS 1.2 [RFC6347] MAY be used.

Proposed Revision:
- If TLS 1.3 cannot be used for compatibility reasons but secure transport over TCP is appropriate, then at least TLS 1.2 [RFC5246] <strike>MUST</strike> SHOULD be used.
- If DTLS 1.3 cannot be used for compatibility reasons but secure transport over UDP is appropriate, then at least DTLS 1.2 [RFC6347] <strike>MUST</strike> SHOULD be used.

To Discuss: should we use MUST or SHOULD in the second set of assertions, consistent with the other assertions?  In an ideal world we would insist on (D)TLS but I know there are situations when they are not possible or inconvenient to use, e.g. on a LAN).  See below.  Currently to not change the original intent (and keeping the change editorial) I am intending to use SHOULD.  The original intent of the "MAY" was to *allow* downgrading to 1.2, with the 1.3 assertions taking priority.  But this breaks if the DTLS-1.3 assertion gets removed.

**Comment by mmccool** [comment]
@j1y3p4rk @JKRhb can you please comment on the MUST/SHOULD issue I noted above?  If I don't hear back I will go with SHOULD for the revisions.  Sorry we ran out of time in the meeting today to discuss, but given the cancellation next week and the pending CR I want to get this done sooner.  I want to keep the change editorial - meaning I don't want to change the intended meaning of these assertions.

**Comment by j1y3p4rk** [comment]
For now, I think we can go for SHOULD to align with other assertions. But eventually I suggest to have TLS/DTLS as mandatory, meaning MUST. We are considering the LAN case where TLS/DTLS usage is limited. I see the limitation only when TLS/DTLS is doing certificate based handshake (when trust anchor check is required), and PSK or Raw-public key based handshake are not the case. We can discuss about it in our security.

**Comment by mmccool** [comment]
I agree personally about making TLS mandatory, but at this point I just want to fix the problem with the at-risk DTLS assertion and the ambiguity that would result if it goes away.  I don't want to change the intent of the text.

**Comment by j1y3p4rk** [comment]
Yes, I agree. For now SHOULD is fine.

**Comment by mmccool** [comment]
It seems we agree, so I have created a PR with the SHOULD wording (see link above; if merged, it will close this issue).
