### ISSUE TITLE
Integration Patterns

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-architecture#9]
There was a lot of feedback that the [Integration Patterns](https://www.w3.org/Submission/wot-model/#web-things-integration-patterns) were helpful to people. Mozilla created a somewhat cleaner [image](https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/06/wot_integration_patterns.png).

I also think it is useful and we should include it in the architecture, probably in the beginning before the Servient architecture. However, we should remove the "thing-to-cloud" focus, as we also need local connectivity (or "edge connectivity").

I will try to come up with  figure. Can we add such a "Integration Patterns" section?

**Comment by mmccool** [comment]
I think this makes sense.   The use cases given are very specific, I think it would be useful to talk about some small number of patterns and then define the use cases in terms of those patterns.

I think it would also be useful to give a more complex use case that combines multiple patterns (eg both local and remote access).   We probably also want to say something about robustness when external internet connectivity is intermittent (that could be used to motivate the "shadow" pattern).

**Comment by mlagally** [comment]
Arch call on 13.2.:
It would be nice to have a similar image in the introduction.

**Comment by mkovatsc** [comment]
Was only "nice to have". Closing.
